"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
* Represents a website for additional scan targets.
*/
class AdditionalWebsiteModel {
    static getAttributeTypeMap() {
        return AdditionalWebsiteModel.attributeTypeMap;
    }
}
AdditionalWebsiteModel.discriminator = undefined;
AdditionalWebsiteModel.attributeTypeMap = [
    {
        "name": "canonical",
        "baseName": "Canonical",
        "type": "boolean"
    },
    {
        "name": "targetUrl",
        "baseName": "TargetUrl",
        "type": "string"
    }
];
exports.AdditionalWebsiteModel = AdditionalWebsiteModel;
//# sourceMappingURL=additionalWebsiteModel.js.map