"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
class AsanaUser {
    static getAttributeTypeMap() {
        return AsanaUser.attributeTypeMap;
    }
}
AsanaUser.discriminator = undefined;
AsanaUser.attributeTypeMap = [
    {
        "name": "email",
        "baseName": "email",
        "type": "string"
    },
    {
        "name": "gid",
        "baseName": "gid",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "displayName",
        "baseName": "DisplayName",
        "type": "string"
    }
];
exports.AsanaUser = AsanaUser;
//# sourceMappingURL=asanaUser.js.map