"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
* Represents authorization code table model for oauth2.
*/
class AuthorizationCodeTableModel {
    static getAttributeTypeMap() {
        return AuthorizationCodeTableModel.attributeTypeMap;
    }
}
AuthorizationCodeTableModel.discriminator = undefined;
AuthorizationCodeTableModel.attributeTypeMap = [
    {
        "name": "fields",
        "baseName": "Fields",
        "type": "Array<string>"
    },
    {
        "name": "items",
        "baseName": "Items",
        "type": "Array<NameValuePair>"
    }
];
exports.AuthorizationCodeTableModel = AuthorizationCodeTableModel;
//# sourceMappingURL=authorizationCodeTableModel.js.map