"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
* Represents a model for carrying out custom 404 settings.
*/
class Custom404SettingModel {
    static getAttributeTypeMap() {
        return Custom404SettingModel.attributeTypeMap;
    }
}
Custom404SettingModel.discriminator = undefined;
Custom404SettingModel.attributeTypeMap = [
    {
        "name": "custom404RegEx",
        "baseName": "Custom404RegEx",
        "type": "string"
    },
    {
        "name": "disableAuto404Detection",
        "baseName": "DisableAuto404Detection",
        "type": "boolean"
    },
    {
        "name": "max404PagesToTest",
        "baseName": "Max404PagesToTest",
        "type": "number"
    },
    {
        "name": "maximum404Signature",
        "baseName": "Maximum404Signature",
        "type": "number"
    }
];
exports.Custom404SettingModel = Custom404SettingModel;
//# sourceMappingURL=custom404SettingModel.js.map