/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Represents a model for carrying out custom 404 settings.
*/
export class Custom404SettingModel {
    /**
    * Gets or sets the Custom 404 RegEx.
    */
    'custom404RegEx'?: string;
    /**
    * Gets or sets a value indicating whether Auto 404 detection is disabled.
    */
    'disableAuto404Detection'?: boolean;
    /**
    * Gets or sets the maximum 404 pages to test.
    */
    'max404PagesToTest': number;
    /**
    * Gets or sets the maximum 404 signature.
    */
    'maximum404Signature': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "custom404RegEx",
            "baseName": "Custom404RegEx",
            "type": "string"
        },
        {
            "name": "disableAuto404Detection",
            "baseName": "DisableAuto404Detection",
            "type": "boolean"
        },
        {
            "name": "max404PagesToTest",
            "baseName": "Max404PagesToTest",
            "type": "number"
        },
        {
            "name": "maximum404Signature",
            "baseName": "Maximum404Signature",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Custom404SettingModel.attributeTypeMap;
    }
}

