"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
* Represents a key/value pair of custom data associated with a vulnerability.
*/
class CustomFieldModel {
    static getAttributeTypeMap() {
        return CustomFieldModel.attributeTypeMap;
    }
}
CustomFieldModel.discriminator = undefined;
CustomFieldModel.attributeTypeMap = [
    {
        "name": "name",
        "baseName": "Name",
        "type": "string"
    },
    {
        "name": "values",
        "baseName": "Values",
        "type": "Array<string>"
    }
];
exports.CustomFieldModel = CustomFieldModel;
//# sourceMappingURL=customFieldModel.js.map