"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
* Represents an email address pattern which is used to ignore email disclosure issues.
*/
class EmailPatternSetting {
    static getAttributeTypeMap() {
        return EmailPatternSetting.attributeTypeMap;
    }
}
EmailPatternSetting.discriminator = undefined;
EmailPatternSetting.attributeTypeMap = [
    {
        "name": "value",
        "baseName": "Value",
        "type": "string"
    }
];
exports.EmailPatternSetting = EmailPatternSetting;
//# sourceMappingURL=emailPatternSetting.js.map