"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
* Exclude filter.
*/
class ExcludeFilter {
    static getAttributeTypeMap() {
        return ExcludeFilter.attributeTypeMap;
    }
}
ExcludeFilter.discriminator = undefined;
ExcludeFilter.attributeTypeMap = [
    {
        "name": "excludedSlds",
        "baseName": "ExcludedSlds",
        "type": "Array<string>"
    },
    {
        "name": "excludedTlds",
        "baseName": "ExcludedTlds",
        "type": "Array<string>"
    },
    {
        "name": "excludedIpAddresses",
        "baseName": "ExcludedIpAddresses",
        "type": "Array<string>"
    },
    {
        "name": "excludedDomains",
        "baseName": "ExcludedDomains",
        "type": "Array<string>"
    },
    {
        "name": "excludedOrganizations",
        "baseName": "ExcludedOrganizations",
        "type": "Array<string>"
    }
];
exports.ExcludeFilter = ExcludeFilter;
//# sourceMappingURL=excludeFilter.js.map