/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* FormAuthenticationHashicorpVaultSetting
*/
export class FormAuthenticationHashicorpVaultSetting {
    /**
    * Gets or sets the integration id.
    */
    'integrationId'?: string;
    /**
    * Gets or sets the KV Secret engine version.
    */
    'version'?: FormAuthenticationHashicorpVaultSetting.VersionEnum;
    /**
    * Gets or sets the secret engine.
    */
    'secretEngine'?: string;
    /**
    * Gets or sets the secret.
    */
    'secret'?: string;
    /**
    * Gets or sets the username is static or not.
    */
    'useStaticUsername'?: boolean;
    /**
    * Gets or sets the static username.
    */
    'staticUsername'?: string;
    /**
    * Gets or sets the username key.
    */
    'usernameKey'?: string;
    /**
    * Gets or sets the password key.
    */
    'passwordKey'?: string;
    'url'?: string;
    'token'?: string;
    'agentMode'?: FormAuthenticationHashicorpVaultSetting.AgentModeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "integrationId",
            "baseName": "IntegrationId",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "Version",
            "type": "FormAuthenticationHashicorpVaultSetting.VersionEnum"
        },
        {
            "name": "secretEngine",
            "baseName": "SecretEngine",
            "type": "string"
        },
        {
            "name": "secret",
            "baseName": "Secret",
            "type": "string"
        },
        {
            "name": "useStaticUsername",
            "baseName": "UseStaticUsername",
            "type": "boolean"
        },
        {
            "name": "staticUsername",
            "baseName": "StaticUsername",
            "type": "string"
        },
        {
            "name": "usernameKey",
            "baseName": "UsernameKey",
            "type": "string"
        },
        {
            "name": "passwordKey",
            "baseName": "PasswordKey",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "Url",
            "type": "string"
        },
        {
            "name": "token",
            "baseName": "Token",
            "type": "string"
        },
        {
            "name": "agentMode",
            "baseName": "AgentMode",
            "type": "FormAuthenticationHashicorpVaultSetting.AgentModeEnum"
        }    ];

    static getAttributeTypeMap() {
        return FormAuthenticationHashicorpVaultSetting.attributeTypeMap;
    }
}

export namespace FormAuthenticationHashicorpVaultSetting {
    export enum VersionEnum {
        V1 = <any> 'V1',
        V2 = <any> 'V2'
    }
    export enum AgentModeEnum {
        Cloud = <any> 'Cloud',
        Internal = <any> 'Internal'
    }
}
