"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
* Represents a class that carries vulnerability information.
*/
class IssueApiUpdateModel {
    static getAttributeTypeMap() {
        return IssueApiUpdateModel.attributeTypeMap;
    }
}
IssueApiUpdateModel.discriminator = undefined;
IssueApiUpdateModel.attributeTypeMap = [
    {
        "name": "issueId",
        "baseName": "IssueId",
        "type": "string"
    },
    {
        "name": "state",
        "baseName": "State",
        "type": "string"
    },
    {
        "name": "assigneeId",
        "baseName": "AssigneeId",
        "type": "string"
    },
    {
        "name": "note",
        "baseName": "Note",
        "type": "string"
    },
    {
        "name": "tags",
        "baseName": "Tags",
        "type": "Array<string>"
    }
];
exports.IssueApiUpdateModel = IssueApiUpdateModel;
//# sourceMappingURL=issueApiUpdateModel.js.map