"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IssueApiModelCvssVector = void 0;
/**
* Gets the parsed cvss vector
*/
class IssueApiModelCvssVector {
    static getAttributeTypeMap() {
        return IssueApiModelCvssVector.attributeTypeMap;
    }
}
exports.IssueApiModelCvssVector = IssueApiModelCvssVector;
IssueApiModelCvssVector.discriminator = undefined;
IssueApiModelCvssVector.attributeTypeMap = [
    {
        "name": "base",
        "baseName": "Base",
        "type": "CvssMetricModel"
    },
    {
        "name": "temporal",
        "baseName": "Temporal",
        "type": "CvssMetricModel"
    },
    {
        "name": "environmental",
        "baseName": "Environmental",
        "type": "CvssMetricModel"
    }
];
//# sourceMappingURL=issueApiModelCvssVector.js.map