"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
* Represents a name / value pair model
*/
class NameValuePair {
    static getAttributeTypeMap() {
        return NameValuePair.attributeTypeMap;
    }
}
NameValuePair.discriminator = undefined;
NameValuePair.attributeTypeMap = [
    {
        "name": "name",
        "baseName": "Name",
        "type": "string"
    },
    {
        "name": "value",
        "baseName": "Value",
        "type": "string"
    },
    {
        "name": "isEncrypted",
        "baseName": "IsEncrypted",
        "type": "boolean"
    }
];
exports.NameValuePair = NameValuePair;
//# sourceMappingURL=nameValuePair.js.map