"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
* Represents a model for creating a new website group.
*/
class NewWebsiteGroupApiModel {
    static getAttributeTypeMap() {
        return NewWebsiteGroupApiModel.attributeTypeMap;
    }
}
NewWebsiteGroupApiModel.discriminator = undefined;
NewWebsiteGroupApiModel.attributeTypeMap = [
    {
        "name": "name",
        "baseName": "Name",
        "type": "string"
    },
    {
        "name": "description",
        "baseName": "Description",
        "type": "string"
    }
];
exports.NewWebsiteGroupApiModel = NewWebsiteGroupApiModel;
//# sourceMappingURL=newWebsiteGroupApiModel.js.map