"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PagerDutyIntegrationInfoModel = void 0;
/**
* The PagerDuty integration info
*/
class PagerDutyIntegrationInfoModel {
    static getAttributeTypeMap() {
        return PagerDutyIntegrationInfoModel.attributeTypeMap;
    }
}
exports.PagerDutyIntegrationInfoModel = PagerDutyIntegrationInfoModel;
PagerDutyIntegrationInfoModel.discriminator = undefined;
PagerDutyIntegrationInfoModel.attributeTypeMap = [
    {
        "name": "apiAccessKey",
        "baseName": "ApiAccessKey",
        "type": "string"
    },
    {
        "name": "apiUrl",
        "baseName": "ApiUrl",
        "type": "string"
    },
    {
        "name": "bodyDetails",
        "baseName": "BodyDetails",
        "type": "string"
    },
    {
        "name": "from",
        "baseName": "From",
        "type": "string"
    },
    {
        "name": "incidentBodyType",
        "baseName": "IncidentBodyType",
        "type": "string"
    },
    {
        "name": "incidentType",
        "baseName": "IncidentType",
        "type": "string"
    },
    {
        "name": "serviceId",
        "baseName": "ServiceId",
        "type": "string"
    },
    {
        "name": "serviceType",
        "baseName": "ServiceType",
        "type": "PagerDutyIntegrationInfoModel.ServiceTypeEnum"
    },
    {
        "name": "title",
        "baseName": "Title",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "Type",
        "type": "PagerDutyIntegrationInfoModel.TypeEnum"
    },
    {
        "name": "urgency",
        "baseName": "Urgency",
        "type": "PagerDutyIntegrationInfoModel.UrgencyEnum"
    },
    {
        "name": "url",
        "baseName": "Url",
        "type": "string"
    },
    {
        "name": "accountID",
        "baseName": "AccountID",
        "type": "string"
    },
    {
        "name": "customFields",
        "baseName": "CustomFields",
        "type": "Array<NotificationIntegrationCustomFieldModel>"
    },
    {
        "name": "genericErrorMessage",
        "baseName": "GenericErrorMessage",
        "type": "string"
    },
    {
        "name": "identifier",
        "baseName": "Identifier",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "Name",
        "type": "string"
    },
    {
        "name": "reopenStatus",
        "baseName": "ReopenStatus",
        "type": "string"
    },
    {
        "name": "integrationWizardResultModel",
        "baseName": "IntegrationWizardResultModel",
        "type": "IntegrationWizardResultModel"
    },
    {
        "name": "resolvedStatus",
        "baseName": "ResolvedStatus",
        "type": "string"
    },
    {
        "name": "testMessageBody",
        "baseName": "TestMessageBody",
        "type": "string"
    },
    {
        "name": "testMessageTitle",
        "baseName": "TestMessageTitle",
        "type": "string"
    },
    {
        "name": "titleFormat",
        "baseName": "TitleFormat",
        "type": "string"
    },
    {
        "name": "webhookUrl",
        "baseName": "WebhookUrl",
        "type": "string"
    }
];
(function (PagerDutyIntegrationInfoModel) {
    let ServiceTypeEnum;
    (function (ServiceTypeEnum) {
        ServiceTypeEnum[ServiceTypeEnum["Service"] = 'service'] = "Service";
        ServiceTypeEnum[ServiceTypeEnum["ServiceReference"] = 'service_reference'] = "ServiceReference";
    })(ServiceTypeEnum = PagerDutyIntegrationInfoModel.ServiceTypeEnum || (PagerDutyIntegrationInfoModel.ServiceTypeEnum = {}));
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum[TypeEnum["Jira"] = 'Jira'] = "Jira";
        TypeEnum[TypeEnum["GitHub"] = 'GitHub'] = "GitHub";
        TypeEnum[TypeEnum["Tfs"] = 'TFS'] = "Tfs";
        TypeEnum[TypeEnum["FogBugz"] = 'FogBugz'] = "FogBugz";
        TypeEnum[TypeEnum["ServiceNow"] = 'ServiceNow'] = "ServiceNow";
        TypeEnum[TypeEnum["Slack"] = 'Slack'] = "Slack";
        TypeEnum[TypeEnum["GitLab"] = 'GitLab'] = "GitLab";
        TypeEnum[TypeEnum["Bitbucket"] = 'Bitbucket'] = "Bitbucket";
        TypeEnum[TypeEnum["Unfuddle"] = 'Unfuddle'] = "Unfuddle";
        TypeEnum[TypeEnum["Zapier"] = 'Zapier'] = "Zapier";
        TypeEnum[TypeEnum["AzureDevOps"] = 'AzureDevOps'] = "AzureDevOps";
        TypeEnum[TypeEnum["Redmine"] = 'Redmine'] = "Redmine";
        TypeEnum[TypeEnum["Bugzilla"] = 'Bugzilla'] = "Bugzilla";
        TypeEnum[TypeEnum["Kafka"] = 'Kafka'] = "Kafka";
        TypeEnum[TypeEnum["PagerDuty"] = 'PagerDuty'] = "PagerDuty";
        TypeEnum[TypeEnum["MicrosoftTeams"] = 'MicrosoftTeams'] = "MicrosoftTeams";
        TypeEnum[TypeEnum["Clubhouse"] = 'Clubhouse'] = "Clubhouse";
        TypeEnum[TypeEnum["Trello"] = 'Trello'] = "Trello";
        TypeEnum[TypeEnum["Asana"] = 'Asana'] = "Asana";
        TypeEnum[TypeEnum["Webhook"] = 'Webhook'] = "Webhook";
        TypeEnum[TypeEnum["Kenna"] = 'Kenna'] = "Kenna";
        TypeEnum[TypeEnum["Freshservice"] = 'Freshservice'] = "Freshservice";
        TypeEnum[TypeEnum["YouTrack"] = 'YouTrack'] = "YouTrack";
        TypeEnum[TypeEnum["NetsparkerEnterprise"] = 'NetsparkerEnterprise'] = "NetsparkerEnterprise";
        TypeEnum[TypeEnum["Splunk"] = 'Splunk'] = "Splunk";
        TypeEnum[TypeEnum["Mattermost"] = 'Mattermost'] = "Mattermost";
        TypeEnum[TypeEnum["Hashicorp"] = 'Hashicorp'] = "Hashicorp";
        TypeEnum[TypeEnum["PivotalTracker"] = 'PivotalTracker'] = "PivotalTracker";
        TypeEnum[TypeEnum["CyberArk"] = 'CyberArk'] = "CyberArk";
    })(TypeEnum = PagerDutyIntegrationInfoModel.TypeEnum || (PagerDutyIntegrationInfoModel.TypeEnum = {}));
    let UrgencyEnum;
    (function (UrgencyEnum) {
        UrgencyEnum[UrgencyEnum["High"] = 'high'] = "High";
        UrgencyEnum[UrgencyEnum["Low"] = 'low'] = "Low";
    })(UrgencyEnum = PagerDutyIntegrationInfoModel.UrgencyEnum || (PagerDutyIntegrationInfoModel.UrgencyEnum = {}));
})(PagerDutyIntegrationInfoModel = exports.PagerDutyIntegrationInfoModel || (exports.PagerDutyIntegrationInfoModel = {}));
//# sourceMappingURL=pagerDutyIntegrationInfoModel.js.map