/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IntegrationWizardResultModel } from './integrationWizardResultModel';
import { NotificationIntegrationCustomFieldModel } from './notificationIntegrationCustomFieldModel';

/**
* The PagerDuty integration info
*/
export class PagerDutyIntegrationInfoModel {
    /**
    * API Access Key for authentication.
    */
    'apiAccessKey': string;
    /**
    * The PagerDuty instance URL.
    */
    'apiUrl'?: string;
    /**
    * The incident will be created on this service type.
    */
    'bodyDetails'?: string;
    /**
    * The email address of a valid user associated with the account making the request.
    */
    'from': string;
    /**
    * Type must be incident_body.
    */
    'incidentBodyType'?: string;
    /**
    * Type must be incident.
    */
    'incidentType'?: string;
    /**
    * The incident will be created on this service id.
    */
    'serviceId': string;
    /**
    * The incident will be created on this service type.
    */
    'serviceType': PagerDutyIntegrationInfoModel.ServiceTypeEnum;
    /**
    * A succinct description of the nature, symptoms, cause, or effect of the incident.
    */
    'title'?: string;
    'type'?: PagerDutyIntegrationInfoModel.TypeEnum;
    /**
    * The urgency of the incident.
    */
    'urgency'?: PagerDutyIntegrationInfoModel.UrgencyEnum;
    /**
    * The PagerDuty instance URL.
    */
    'url': string;
    /**
    * Gets or sets the account ID.
    */
    'accountID'?: string;
    /**
    * Gets or sets the Custom Fields.
    */
    'customFields'?: Array<NotificationIntegrationCustomFieldModel>;
    /**
    * Gets the generic error message.
    */
    'genericErrorMessage'?: string;
    /**
    * Gets or sets the request identifier.
    */
    'identifier'?: string;
    /**
    * Gets or sets the {Invicti.Cloud.Core.Models.ScanNotificationIntegration} name.
    */
    'name'?: string;
    /**
    * Gets or sets the type of the issue.
    */
    'reopenStatus'?: string;
    'integrationWizardResultModel'?: IntegrationWizardResultModel;
    /**
    * Gets or sets the type of the issue.
    */
    'resolvedStatus'?: string;
    /**
    * Gets the test message body.
    */
    'testMessageBody'?: string;
    /**
    * Gets the test message title.
    */
    'testMessageTitle'?: string;
    /**
    * Gets or sets the title format.
    */
    'titleFormat': string;
    /**
    * Gets the webhook URL.
    */
    'webhookUrl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apiAccessKey",
            "baseName": "ApiAccessKey",
            "type": "string"
        },
        {
            "name": "apiUrl",
            "baseName": "ApiUrl",
            "type": "string"
        },
        {
            "name": "bodyDetails",
            "baseName": "BodyDetails",
            "type": "string"
        },
        {
            "name": "from",
            "baseName": "From",
            "type": "string"
        },
        {
            "name": "incidentBodyType",
            "baseName": "IncidentBodyType",
            "type": "string"
        },
        {
            "name": "incidentType",
            "baseName": "IncidentType",
            "type": "string"
        },
        {
            "name": "serviceId",
            "baseName": "ServiceId",
            "type": "string"
        },
        {
            "name": "serviceType",
            "baseName": "ServiceType",
            "type": "PagerDutyIntegrationInfoModel.ServiceTypeEnum"
        },
        {
            "name": "title",
            "baseName": "Title",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "Type",
            "type": "PagerDutyIntegrationInfoModel.TypeEnum"
        },
        {
            "name": "urgency",
            "baseName": "Urgency",
            "type": "PagerDutyIntegrationInfoModel.UrgencyEnum"
        },
        {
            "name": "url",
            "baseName": "Url",
            "type": "string"
        },
        {
            "name": "accountID",
            "baseName": "AccountID",
            "type": "string"
        },
        {
            "name": "customFields",
            "baseName": "CustomFields",
            "type": "Array<NotificationIntegrationCustomFieldModel>"
        },
        {
            "name": "genericErrorMessage",
            "baseName": "GenericErrorMessage",
            "type": "string"
        },
        {
            "name": "identifier",
            "baseName": "Identifier",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "Name",
            "type": "string"
        },
        {
            "name": "reopenStatus",
            "baseName": "ReopenStatus",
            "type": "string"
        },
        {
            "name": "integrationWizardResultModel",
            "baseName": "IntegrationWizardResultModel",
            "type": "IntegrationWizardResultModel"
        },
        {
            "name": "resolvedStatus",
            "baseName": "ResolvedStatus",
            "type": "string"
        },
        {
            "name": "testMessageBody",
            "baseName": "TestMessageBody",
            "type": "string"
        },
        {
            "name": "testMessageTitle",
            "baseName": "TestMessageTitle",
            "type": "string"
        },
        {
            "name": "titleFormat",
            "baseName": "TitleFormat",
            "type": "string"
        },
        {
            "name": "webhookUrl",
            "baseName": "WebhookUrl",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PagerDutyIntegrationInfoModel.attributeTypeMap;
    }
}

export namespace PagerDutyIntegrationInfoModel {
    export enum ServiceTypeEnum {
        Service = <any> 'service',
        ServiceReference = <any> 'service_reference'
    }
    export enum TypeEnum {
        Jira = <any> 'Jira',
        GitHub = <any> 'GitHub',
        Tfs = <any> 'TFS',
        FogBugz = <any> 'FogBugz',
        ServiceNow = <any> 'ServiceNow',
        Slack = <any> 'Slack',
        GitLab = <any> 'GitLab',
        Bitbucket = <any> 'Bitbucket',
        Unfuddle = <any> 'Unfuddle',
        Zapier = <any> 'Zapier',
        AzureDevOps = <any> 'AzureDevOps',
        Redmine = <any> 'Redmine',
        Bugzilla = <any> 'Bugzilla',
        Kafka = <any> 'Kafka',
        PagerDuty = <any> 'PagerDuty',
        MicrosoftTeams = <any> 'MicrosoftTeams',
        Clubhouse = <any> 'Clubhouse',
        Trello = <any> 'Trello',
        Asana = <any> 'Asana',
        Webhook = <any> 'Webhook',
        Kenna = <any> 'Kenna',
        Freshservice = <any> 'Freshservice',
        YouTrack = <any> 'YouTrack',
        NetsparkerEnterprise = <any> 'NetsparkerEnterprise',
        Splunk = <any> 'Splunk',
        Mattermost = <any> 'Mattermost',
        Hashicorp = <any> 'Hashicorp',
        PivotalTracker = <any> 'PivotalTracker',
        CyberArk = <any> 'CyberArk'
    }
    export enum UrgencyEnum {
        High = <any> 'high',
        Low = <any> 'low'
    }
}
