"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PciScanTaskViewModel = void 0;
/**
* Pci Scan Task view model
*/
class PciScanTaskViewModel {
    static getAttributeTypeMap() {
        return PciScanTaskViewModel.attributeTypeMap;
    }
}
exports.PciScanTaskViewModel = PciScanTaskViewModel;
PciScanTaskViewModel.discriminator = undefined;
PciScanTaskViewModel.attributeTypeMap = [
    {
        "name": "name",
        "baseName": "Name",
        "type": "string"
    },
    {
        "name": "progress",
        "baseName": "Progress",
        "type": "number"
    },
    {
        "name": "scanState",
        "baseName": "ScanState",
        "type": "PciScanTaskViewModel.ScanStateEnum"
    },
    {
        "name": "complianceStatus",
        "baseName": "ComplianceStatus",
        "type": "PciScanTaskViewModel.ComplianceStatusEnum"
    },
    {
        "name": "endDate",
        "baseName": "EndDate",
        "type": "Date"
    }
];
(function (PciScanTaskViewModel) {
    let ScanStateEnum;
    (function (ScanStateEnum) {
        ScanStateEnum[ScanStateEnum["New"] = 'New'] = "New";
        ScanStateEnum[ScanStateEnum["Running"] = 'Running'] = "Running";
        ScanStateEnum[ScanStateEnum["Stopped"] = 'Stopped'] = "Stopped";
        ScanStateEnum[ScanStateEnum["Deleted"] = 'Deleted'] = "Deleted";
        ScanStateEnum[ScanStateEnum["Done"] = 'Done'] = "Done";
    })(ScanStateEnum = PciScanTaskViewModel.ScanStateEnum || (PciScanTaskViewModel.ScanStateEnum = {}));
    let ComplianceStatusEnum;
    (function (ComplianceStatusEnum) {
        ComplianceStatusEnum[ComplianceStatusEnum["Scanning"] = 'Scanning'] = "Scanning";
        ComplianceStatusEnum[ComplianceStatusEnum["Passed"] = 'Passed'] = "Passed";
        ComplianceStatusEnum[ComplianceStatusEnum["Failed"] = 'Failed'] = "Failed";
    })(ComplianceStatusEnum = PciScanTaskViewModel.ComplianceStatusEnum || (PciScanTaskViewModel.ComplianceStatusEnum = {}));
})(PciScanTaskViewModel = exports.PciScanTaskViewModel || (exports.PciScanTaskViewModel = {}));
//# sourceMappingURL=pciScanTaskViewModel.js.map