/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Represents a model for carrying out pattern settings.
*/
export class ScanPolicyPatternModel {
    /**
    * Gets or sets the id of the custom script id.
    */
    'customScriptId'?: string;
    /**
    * Gets or sets the description of the security check.
    */
    'description'?: string;
    /**
    * Gets or sets a value indicating whether this instance is enabled.
    */
    'enabled'?: boolean;
    /**
    * Gets or sets the id of the security check.
    */
    'id'?: string;
    /**
    * Gets or sets the name of the security check.
    */
    'name'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "customScriptId",
            "baseName": "CustomScriptId",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "Description",
            "type": "string"
        },
        {
            "name": "enabled",
            "baseName": "Enabled",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "Id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "Name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ScanPolicyPatternModel.attributeTypeMap;
    }
}

