"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
* Represents a model for carrying scan report parameters.
*/
class ScanReportApiModel {
    static getAttributeTypeMap() {
        return ScanReportApiModel.attributeTypeMap;
    }
}
ScanReportApiModel.discriminator = undefined;
ScanReportApiModel.attributeTypeMap = [
    {
        "name": "contentFormat",
        "baseName": "ContentFormat",
        "type": "ScanReportApiModel.ContentFormatEnum"
    },
    {
        "name": "excludeResponseData",
        "baseName": "ExcludeResponseData",
        "type": "boolean"
    },
    {
        "name": "format",
        "baseName": "Format",
        "type": "ScanReportApiModel.FormatEnum"
    },
    {
        "name": "id",
        "baseName": "Id",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "Type",
        "type": "ScanReportApiModel.TypeEnum"
    },
    {
        "name": "onlyConfirmedIssues",
        "baseName": "OnlyConfirmedIssues",
        "type": "boolean"
    },
    {
        "name": "onlyUnconfirmedIssues",
        "baseName": "OnlyUnconfirmedIssues",
        "type": "boolean"
    },
    {
        "name": "excludeAddressedIssues",
        "baseName": "ExcludeAddressedIssues",
        "type": "boolean"
    }
];
exports.ScanReportApiModel = ScanReportApiModel;
(function (ScanReportApiModel) {
    let ContentFormatEnum;
    (function (ContentFormatEnum) {
        ContentFormatEnum[ContentFormatEnum["Html"] = 'Html'] = "Html";
        ContentFormatEnum[ContentFormatEnum["Markdown"] = 'Markdown'] = "Markdown";
    })(ContentFormatEnum = ScanReportApiModel.ContentFormatEnum || (ScanReportApiModel.ContentFormatEnum = {}));
    let FormatEnum;
    (function (FormatEnum) {
        FormatEnum[FormatEnum["Xml"] = 'Xml'] = "Xml";
        FormatEnum[FormatEnum["Csv"] = 'Csv'] = "Csv";
        FormatEnum[FormatEnum["Pdf"] = 'Pdf'] = "Pdf";
        FormatEnum[FormatEnum["Html"] = 'Html'] = "Html";
        FormatEnum[FormatEnum["Txt"] = 'Txt'] = "Txt";
        FormatEnum[FormatEnum["Json"] = 'Json'] = "Json";
    })(FormatEnum = ScanReportApiModel.FormatEnum || (ScanReportApiModel.FormatEnum = {}));
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum[TypeEnum["Crawled"] = 'Crawled'] = "Crawled";
        TypeEnum[TypeEnum["Scanned"] = 'Scanned'] = "Scanned";
        TypeEnum[TypeEnum["Vulnerabilities"] = 'Vulnerabilities'] = "Vulnerabilities";
        TypeEnum[TypeEnum["ScanDetail"] = 'ScanDetail'] = "ScanDetail";
        TypeEnum[TypeEnum["ModSecurityWafRules"] = 'ModSecurityWafRules'] = "ModSecurityWafRules";
        TypeEnum[TypeEnum["OwaspTopTen2013"] = 'OwaspTopTen2013'] = "OwaspTopTen2013";
        TypeEnum[TypeEnum["HipaaCompliance"] = 'HIPAACompliance'] = "HipaaCompliance";
        TypeEnum[TypeEnum["PciCompliance"] = 'PCICompliance'] = "PciCompliance";
        TypeEnum[TypeEnum["KnowledgeBase"] = 'KnowledgeBase'] = "KnowledgeBase";
        TypeEnum[TypeEnum["ExecutiveSummary"] = 'ExecutiveSummary'] = "ExecutiveSummary";
        TypeEnum[TypeEnum["FullScanDetail"] = 'FullScanDetail'] = "FullScanDetail";
        TypeEnum[TypeEnum["OwaspTopTen2017"] = 'OwaspTopTen2017'] = "OwaspTopTen2017";
        TypeEnum[TypeEnum["CustomReport"] = 'CustomReport'] = "CustomReport";
        TypeEnum[TypeEnum["Iso27001Compliance"] = 'Iso27001Compliance'] = "Iso27001Compliance";
        TypeEnum[TypeEnum["F5BigIpAsmWafRules"] = 'F5BigIpAsmWafRules'] = "F5BigIpAsmWafRules";
        TypeEnum[TypeEnum["Wasc"] = 'WASC'] = "Wasc";
        TypeEnum[TypeEnum["SansTop25"] = 'SansTop25'] = "SansTop25";
    })(TypeEnum = ScanReportApiModel.TypeEnum || (ScanReportApiModel.TypeEnum = {}));
})(ScanReportApiModel = exports.ScanReportApiModel || (exports.ScanReportApiModel = {}));
//# sourceMappingURL=scanReportApiModel.js.map