"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SecurityCheckGroupParentModel = void 0;
/**
* Represents a model for carrying out security check groups.
*/
class SecurityCheckGroupParentModel {
    static getAttributeTypeMap() {
        return SecurityCheckGroupParentModel.attributeTypeMap;
    }
}
exports.SecurityCheckGroupParentModel = SecurityCheckGroupParentModel;
SecurityCheckGroupParentModel.discriminator = undefined;
SecurityCheckGroupParentModel.attributeTypeMap = [
    {
        "name": "title",
        "baseName": "Title",
        "type": "string"
    },
    {
        "name": "securityCheckGroups",
        "baseName": "SecurityCheckGroups",
        "type": "Array<SecurityCheckGroupModel>"
    }
];
//# sourceMappingURL=securityCheckGroupParentModel.js.map