"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SelectOptionModel = void 0;
/**
* Represents a name / value pair model.
*/
class SelectOptionModel {
    static getAttributeTypeMap() {
        return SelectOptionModel.attributeTypeMap;
    }
}
exports.SelectOptionModel = SelectOptionModel;
SelectOptionModel.discriminator = undefined;
SelectOptionModel.attributeTypeMap = [
    {
        "name": "label",
        "baseName": "Label",
        "type": "string"
    },
    {
        "name": "value",
        "baseName": "Value",
        "type": "object"
    }
];
//# sourceMappingURL=selectOptionModel.js.map