"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ThreeLeggedFields = void 0;
/**
* Represents 3-legged model for oauth2.
*/
class ThreeLeggedFields {
    static getAttributeTypeMap() {
        return ThreeLeggedFields.attributeTypeMap;
    }
}
exports.ThreeLeggedFields = ThreeLeggedFields;
ThreeLeggedFields.discriminator = undefined;
ThreeLeggedFields.attributeTypeMap = [
    {
        "name": "enabled",
        "baseName": "Enabled",
        "type": "boolean"
    },
    {
        "name": "username",
        "baseName": "Username",
        "type": "string"
    },
    {
        "name": "password",
        "baseName": "Password",
        "type": "string"
    },
    {
        "name": "otpSettings",
        "baseName": "OtpSettings",
        "type": "OtpSettings"
    },
    {
        "name": "customScripts",
        "baseName": "CustomScripts",
        "type": "Array<string>"
    }
];
//# sourceMappingURL=threeLeggedFields.js.map