"use strict";
/**
 * Netsparker Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
* The health check model for user
*/
class UserHealthCheckApiModel {
    static getAttributeTypeMap() {
        return UserHealthCheckApiModel.attributeTypeMap;
    }
}
UserHealthCheckApiModel.discriminator = undefined;
UserHealthCheckApiModel.attributeTypeMap = [
    {
        "name": "dateFormat",
        "baseName": "DateFormat",
        "type": "string"
    },
    {
        "name": "displayName",
        "baseName": "DisplayName",
        "type": "string"
    },
    {
        "name": "email",
        "baseName": "Email",
        "type": "string"
    },
    {
        "name": "timeZoneInfo",
        "baseName": "TimeZoneInfo",
        "type": "string"
    }
];
exports.UserHealthCheckApiModel = UserHealthCheckApiModel;
//# sourceMappingURL=userHealthCheckApiModel.js.map