/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Represents a model for carrying out website group data.
*/
export class WebsiteGroupApiModel {
    /**
    * Gets or sets the total websites.
    */
    'totalWebsites'?: number;
    /**
    * Gets or sets the date which this website group created at.
    */
    'createdAt'?: Date;
    /**
    * Gets or sets the date which this website group was updated at.
    */
    'updatedAt'?: Date;
    /**
    * Gets or sets the website group identifier.
    */
    'id': string;
    /**
    * Gets or sets the website group name.
    */
    'name': string;
    /**
    * Gets or sets the website group description.
    */
    'description'?: string;
    /**
    * Tags
    */
    'tags'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "totalWebsites",
            "baseName": "TotalWebsites",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "CreatedAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "UpdatedAt",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "Id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "Name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "Description",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "Tags",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return WebsiteGroupApiModel.attributeTypeMap;
    }
}

