/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Represents a model for carrying out input auto complete settings.
 * @export
 * @interface ContentTypeModel
 */
export interface ContentTypeModel {
    /**
     * Gets or sets the content type.
     * @type {string}
     * @memberof ContentTypeModel
     */
    value: string;
}

/**
 * Check if a given object implements the ContentTypeModel interface.
 */
export function instanceOfContentTypeModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function ContentTypeModelFromJSON(json: any): ContentTypeModel {
    return ContentTypeModelFromJSONTyped(json, false);
}

export function ContentTypeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentTypeModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['Value'],
    };
}

export function ContentTypeModelToJSON(value?: ContentTypeModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Value': value.value,
    };
}

