/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CvssScoreValue
 */
export interface CvssScoreValue {
    /**
     * 
     * @type {string}
     * @memberof CvssScoreValue
     */
    readonly severity?: CvssScoreValueSeverityEnum;
    /**
     * 
     * @type {number}
     * @memberof CvssScoreValue
     */
    readonly value?: number;
}


/**
 * @export
 */
export const CvssScoreValueSeverityEnum = {
    None: 'None',
    Low: 'Low',
    Medium: 'Medium',
    High: 'High',
    Critical: 'Critical'
} as const;
export type CvssScoreValueSeverityEnum = typeof CvssScoreValueSeverityEnum[keyof typeof CvssScoreValueSeverityEnum];


/**
 * Check if a given object implements the CvssScoreValue interface.
 */
export function instanceOfCvssScoreValue(value: object): boolean {
    return true;
}

export function CvssScoreValueFromJSON(json: any): CvssScoreValue {
    return CvssScoreValueFromJSONTyped(json, false);
}

export function CvssScoreValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CvssScoreValue {
    if (json == null) {
        return json;
    }
    return {
        
        'severity': json['Severity'] == null ? undefined : json['Severity'],
        'value': json['Value'] == null ? undefined : json['Value'],
    };
}

export function CvssScoreValueToJSON(value?: Omit<CvssScoreValue, 'Severity'|'Value'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

