/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IntegrationWizardResultModel } from './IntegrationWizardResultModel';
import {
    IntegrationWizardResultModelFromJSON,
    IntegrationWizardResultModelFromJSONTyped,
    IntegrationWizardResultModelToJSON,
} from './IntegrationWizardResultModel';
import type { IntegrationCustomFieldVm } from './IntegrationCustomFieldVm';
import {
    IntegrationCustomFieldVmFromJSON,
    IntegrationCustomFieldVmFromJSONTyped,
    IntegrationCustomFieldVmToJSON,
} from './IntegrationCustomFieldVm';

/**
 * 
 * @export
 * @interface CyberArkVaultIntegrationInfoModel
 */
export interface CyberArkVaultIntegrationInfoModel {
    /**
     * 
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    certificateFileKey?: string;
    /**
     * Pfx File Password for authentication.
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    certificateFilePassword?: string;
    /**
     * The Vault instance URL.
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    agentMode?: CyberArkVaultIntegrationInfoModelAgentModeEnum;
    /**
     * 
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    readonly type?: CyberArkVaultIntegrationInfoModelTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    readonly genericErrorMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    readonly identifier?: string;
    /**
     * 
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    readonly testMessageBody?: string;
    /**
     * 
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    readonly testMessageTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    readonly webhookUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    integrationVersion?: number;
    /**
     * 
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    accountID?: string;
    /**
     * 
     * @type {Array<IntegrationCustomFieldVm>}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    customFields?: Array<IntegrationCustomFieldVm>;
    /**
     * 
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    templateType?: CyberArkVaultIntegrationInfoModelTemplateTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    reopenStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    resolvedStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    titleFormat: string;
    /**
     * 
     * @type {IntegrationWizardResultModel}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    integrationWizardResultModel?: IntegrationWizardResultModel;
    /**
     * 
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CyberArkVaultIntegrationInfoModel
     */
    state?: CyberArkVaultIntegrationInfoModelStateEnum;
}


/**
 * @export
 */
export const CyberArkVaultIntegrationInfoModelAgentModeEnum = {
    Cloud: 'Cloud',
    Internal: 'Internal'
} as const;
export type CyberArkVaultIntegrationInfoModelAgentModeEnum = typeof CyberArkVaultIntegrationInfoModelAgentModeEnum[keyof typeof CyberArkVaultIntegrationInfoModelAgentModeEnum];

/**
 * @export
 */
export const CyberArkVaultIntegrationInfoModelTypeEnum = {
    Jira: 'Jira',
    GitHub: 'GitHub',
    Tfs: 'TFS',
    FogBugz: 'FogBugz',
    ServiceNow: 'ServiceNow',
    Slack: 'Slack',
    GitLab: 'GitLab',
    Bitbucket: 'Bitbucket',
    Unfuddle: 'Unfuddle',
    Zapier: 'Zapier',
    AzureDevOps: 'AzureDevOps',
    Redmine: 'Redmine',
    Bugzilla: 'Bugzilla',
    Kafka: 'Kafka',
    PagerDuty: 'PagerDuty',
    MicrosoftTeams: 'MicrosoftTeams',
    Clubhouse: 'Clubhouse',
    Trello: 'Trello',
    Asana: 'Asana',
    Webhook: 'Webhook',
    Kenna: 'Kenna',
    Freshservice: 'Freshservice',
    YouTrack: 'YouTrack',
    NetsparkerEnterprise: 'NetsparkerEnterprise',
    Splunk: 'Splunk',
    Mattermost: 'Mattermost',
    Hashicorp: 'Hashicorp',
    PivotalTracker: 'PivotalTracker',
    CyberArk: 'CyberArk',
    DefectDojo: 'DefectDojo',
    JazzTeam: 'JazzTeam',
    AzureKeyVault: 'AzureKeyVault',
    ServiceNowVrm: 'ServiceNowVRM'
} as const;
export type CyberArkVaultIntegrationInfoModelTypeEnum = typeof CyberArkVaultIntegrationInfoModelTypeEnum[keyof typeof CyberArkVaultIntegrationInfoModelTypeEnum];

/**
 * @export
 */
export const CyberArkVaultIntegrationInfoModelTemplateTypeEnum = {
    Standard: 'Standard',
    Detailed: 'Detailed'
} as const;
export type CyberArkVaultIntegrationInfoModelTemplateTypeEnum = typeof CyberArkVaultIntegrationInfoModelTemplateTypeEnum[keyof typeof CyberArkVaultIntegrationInfoModelTemplateTypeEnum];

/**
 * @export
 */
export const CyberArkVaultIntegrationInfoModelStateEnum = {
    Active: 'Active',
    Suspended: 'Suspended'
} as const;
export type CyberArkVaultIntegrationInfoModelStateEnum = typeof CyberArkVaultIntegrationInfoModelStateEnum[keyof typeof CyberArkVaultIntegrationInfoModelStateEnum];


/**
 * Check if a given object implements the CyberArkVaultIntegrationInfoModel interface.
 */
export function instanceOfCyberArkVaultIntegrationInfoModel(value: object): boolean {
    if (!('url' in value)) return false;
    if (!('titleFormat' in value)) return false;
    return true;
}

export function CyberArkVaultIntegrationInfoModelFromJSON(json: any): CyberArkVaultIntegrationInfoModel {
    return CyberArkVaultIntegrationInfoModelFromJSONTyped(json, false);
}

export function CyberArkVaultIntegrationInfoModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CyberArkVaultIntegrationInfoModel {
    if (json == null) {
        return json;
    }
    return {
        
        'certificateFileKey': json['CertificateFileKey'] == null ? undefined : json['CertificateFileKey'],
        'certificateFilePassword': json['CertificateFilePassword'] == null ? undefined : json['CertificateFilePassword'],
        'url': json['Url'],
        'agentMode': json['AgentMode'] == null ? undefined : json['AgentMode'],
        'type': json['Type'] == null ? undefined : json['Type'],
        'genericErrorMessage': json['GenericErrorMessage'] == null ? undefined : json['GenericErrorMessage'],
        'identifier': json['Identifier'] == null ? undefined : json['Identifier'],
        'testMessageBody': json['TestMessageBody'] == null ? undefined : json['TestMessageBody'],
        'testMessageTitle': json['TestMessageTitle'] == null ? undefined : json['TestMessageTitle'],
        'webhookUrl': json['WebhookUrl'] == null ? undefined : json['WebhookUrl'],
        'name': json['Name'] == null ? undefined : json['Name'],
        'integrationVersion': json['IntegrationVersion'] == null ? undefined : json['IntegrationVersion'],
        'accountID': json['AccountID'] == null ? undefined : json['AccountID'],
        'customFields': json['CustomFields'] == null ? undefined : ((json['CustomFields'] as Array<any>).map(IntegrationCustomFieldVmFromJSON)),
        'templateType': json['TemplateType'] == null ? undefined : json['TemplateType'],
        'reopenStatus': json['ReopenStatus'] == null ? undefined : json['ReopenStatus'],
        'resolvedStatus': json['ResolvedStatus'] == null ? undefined : json['ResolvedStatus'],
        'titleFormat': json['TitleFormat'],
        'integrationWizardResultModel': json['IntegrationWizardResultModel'] == null ? undefined : IntegrationWizardResultModelFromJSON(json['IntegrationWizardResultModel']),
        'id': json['Id'] == null ? undefined : json['Id'],
        'state': json['State'] == null ? undefined : json['State'],
    };
}

export function CyberArkVaultIntegrationInfoModelToJSON(value?: Omit<CyberArkVaultIntegrationInfoModel, 'Type'|'GenericErrorMessage'|'Identifier'|'TestMessageBody'|'TestMessageTitle'|'WebhookUrl'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'CertificateFileKey': value['certificateFileKey'],
        'CertificateFilePassword': value['certificateFilePassword'],
        'Url': value['url'],
        'AgentMode': value['agentMode'],
        'Name': value['name'],
        'IntegrationVersion': value['integrationVersion'],
        'AccountID': value['accountID'],
        'CustomFields': value['customFields'] == null ? undefined : ((value['customFields'] as Array<any>).map(IntegrationCustomFieldVmToJSON)),
        'TemplateType': value['templateType'],
        'ReopenStatus': value['reopenStatus'],
        'ResolvedStatus': value['resolvedStatus'],
        'TitleFormat': value['titleFormat'],
        'IntegrationWizardResultModel': IntegrationWizardResultModelToJSON(value['integrationWizardResultModel']),
        'Id': value['id'],
        'State': value['state'],
    };
}

