/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiscoveryConnectionsApiModel } from './DiscoveryConnectionsApiModel';
import {
    DiscoveryConnectionsApiModelFromJSON,
    DiscoveryConnectionsApiModelFromJSONTyped,
    DiscoveryConnectionsApiModelToJSON,
} from './DiscoveryConnectionsApiModel';

/**
 * 
 * @export
 * @interface DiscoveryApiModel
 */
export interface DiscoveryApiModel {
    /**
     * Gets or sets the identifier.
     * @type {string}
     * @memberof DiscoveryApiModel
     */
    id?: string;
    /**
     * Gets or sets the sub domain.
     * @type {string}
     * @memberof DiscoveryApiModel
     */
    subDomain?: string;
    /**
     * Gets or sets the second level domain.
     * @type {string}
     * @memberof DiscoveryApiModel
     */
    secondLevelDomain?: string;
    /**
     * Gets or sets the second level domain count.
     * @type {number}
     * @memberof DiscoveryApiModel
     */
    secondLevelDomainCount?: number;
    /**
     * Gets or sets the top level domain.
     * @type {string}
     * @memberof DiscoveryApiModel
     */
    topLevelDomain?: string;
    /**
     * Gets or sets the top level domain count.
     * @type {number}
     * @memberof DiscoveryApiModel
     */
    topLevelDomainCount?: number;
    /**
     * Gets or sets the authority.
     * @type {string}
     * @memberof DiscoveryApiModel
     */
    authority?: string;
    /**
     * Gets or sets the HTTPS.
     * @type {boolean}
     * @memberof DiscoveryApiModel
     */
    https?: boolean;
    /**
     * Gets the ip address string.
     * @type {string}
     * @memberof DiscoveryApiModel
     */
    ipAddress?: string;
    /**
     * Gets the ip address count.
     * @type {number}
     * @memberof DiscoveryApiModel
     */
    readonly ipAddressCount?: number;
    /**
     * Gets or sets the name of the organization.
     * @type {string}
     * @memberof DiscoveryApiModel
     */
    organizationName?: string;
    /**
     * Gets or sets the organization name count.
     * @type {number}
     * @memberof DiscoveryApiModel
     */
    organizationNameCount?: number;
    /**
     * Gets or sets the copyright.
     * @type {string}
     * @memberof DiscoveryApiModel
     */
    copyright?: string;
    /**
     * Gets or sets the account identifier.
     * @type {string}
     * @memberof DiscoveryApiModel
     */
    accountId?: string;
    /**
     * Gets or sets the website identifier.
     * @type {string}
     * @memberof DiscoveryApiModel
     */
    websiteId?: string;
    /**
     * Gets or sets the name of the website.
     * @type {string}
     * @memberof DiscoveryApiModel
     */
    websiteName?: string;
    /**
     * Gets or sets the distance.
     * @type {number}
     * @memberof DiscoveryApiModel
     */
    distance?: number;
    /**
     * Gets or sets the status.
     * @type {string}
     * @memberof DiscoveryApiModel
     */
    status?: DiscoveryApiModelStatusEnum;
    /**
     * Gets or sets the tags
     * @type {Array<string>}
     * @memberof DiscoveryApiModel
     */
    tags?: Array<string>;
    /**
     * Gets or sets the Port of the website.
     * @type {number}
     * @memberof DiscoveryApiModel
     */
    port?: number;
    /**
     * Gets or sets the Discovery Source Type of the website.
     * @type {string}
     * @memberof DiscoveryApiModel
     */
    discoverySourceType?: DiscoveryApiModelDiscoverySourceTypeEnum;
    /**
     * 
     * @type {DiscoveryConnectionsApiModel}
     * @memberof DiscoveryApiModel
     */
    discoveryConnectionsDetail?: DiscoveryConnectionsApiModel;
    /**
     * Gets or sets the risk score of the website.
     * @type {string}
     * @memberof DiscoveryApiModel
     */
    riskScore?: DiscoveryApiModelRiskScoreEnum;
}


/**
 * @export
 */
export const DiscoveryApiModelStatusEnum = {
    Discovered: 'Discovered',
    Ignored: 'Ignored',
    Created: 'Created'
} as const;
export type DiscoveryApiModelStatusEnum = typeof DiscoveryApiModelStatusEnum[keyof typeof DiscoveryApiModelStatusEnum];

/**
 * @export
 */
export const DiscoveryApiModelDiscoverySourceTypeEnum = {
    RadarDeepInfo: 'RadarDeepInfo',
    Aws: 'Aws'
} as const;
export type DiscoveryApiModelDiscoverySourceTypeEnum = typeof DiscoveryApiModelDiscoverySourceTypeEnum[keyof typeof DiscoveryApiModelDiscoverySourceTypeEnum];

/**
 * @export
 */
export const DiscoveryApiModelRiskScoreEnum = {
    Low: 'Low',
    Medium: 'Medium',
    High: 'High',
    Critical: 'Critical',
    Loading: 'Loading',
    Undetermined: 'Undetermined',
    TemporaryUnavailable: 'TemporaryUnavailable'
} as const;
export type DiscoveryApiModelRiskScoreEnum = typeof DiscoveryApiModelRiskScoreEnum[keyof typeof DiscoveryApiModelRiskScoreEnum];


/**
 * Check if a given object implements the DiscoveryApiModel interface.
 */
export function instanceOfDiscoveryApiModel(value: object): boolean {
    return true;
}

export function DiscoveryApiModelFromJSON(json: any): DiscoveryApiModel {
    return DiscoveryApiModelFromJSONTyped(json, false);
}

export function DiscoveryApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveryApiModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['Id'] == null ? undefined : json['Id'],
        'subDomain': json['SubDomain'] == null ? undefined : json['SubDomain'],
        'secondLevelDomain': json['SecondLevelDomain'] == null ? undefined : json['SecondLevelDomain'],
        'secondLevelDomainCount': json['SecondLevelDomainCount'] == null ? undefined : json['SecondLevelDomainCount'],
        'topLevelDomain': json['TopLevelDomain'] == null ? undefined : json['TopLevelDomain'],
        'topLevelDomainCount': json['TopLevelDomainCount'] == null ? undefined : json['TopLevelDomainCount'],
        'authority': json['Authority'] == null ? undefined : json['Authority'],
        'https': json['Https'] == null ? undefined : json['Https'],
        'ipAddress': json['IpAddress'] == null ? undefined : json['IpAddress'],
        'ipAddressCount': json['IpAddressCount'] == null ? undefined : json['IpAddressCount'],
        'organizationName': json['OrganizationName'] == null ? undefined : json['OrganizationName'],
        'organizationNameCount': json['OrganizationNameCount'] == null ? undefined : json['OrganizationNameCount'],
        'copyright': json['Copyright'] == null ? undefined : json['Copyright'],
        'accountId': json['AccountId'] == null ? undefined : json['AccountId'],
        'websiteId': json['WebsiteId'] == null ? undefined : json['WebsiteId'],
        'websiteName': json['WebsiteName'] == null ? undefined : json['WebsiteName'],
        'distance': json['Distance'] == null ? undefined : json['Distance'],
        'status': json['Status'] == null ? undefined : json['Status'],
        'tags': json['Tags'] == null ? undefined : json['Tags'],
        'port': json['Port'] == null ? undefined : json['Port'],
        'discoverySourceType': json['DiscoverySourceType'] == null ? undefined : json['DiscoverySourceType'],
        'discoveryConnectionsDetail': json['DiscoveryConnectionsDetail'] == null ? undefined : DiscoveryConnectionsApiModelFromJSON(json['DiscoveryConnectionsDetail']),
        'riskScore': json['RiskScore'] == null ? undefined : json['RiskScore'],
    };
}

export function DiscoveryApiModelToJSON(value?: Omit<DiscoveryApiModel, 'IpAddressCount'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'Id': value['id'],
        'SubDomain': value['subDomain'],
        'SecondLevelDomain': value['secondLevelDomain'],
        'SecondLevelDomainCount': value['secondLevelDomainCount'],
        'TopLevelDomain': value['topLevelDomain'],
        'TopLevelDomainCount': value['topLevelDomainCount'],
        'Authority': value['authority'],
        'Https': value['https'],
        'IpAddress': value['ipAddress'],
        'OrganizationName': value['organizationName'],
        'OrganizationNameCount': value['organizationNameCount'],
        'Copyright': value['copyright'],
        'AccountId': value['accountId'],
        'WebsiteId': value['websiteId'],
        'WebsiteName': value['websiteName'],
        'Distance': value['distance'],
        'Status': value['status'],
        'Tags': value['tags'],
        'Port': value['port'],
        'DiscoverySourceType': value['discoverySourceType'],
        'DiscoveryConnectionsDetail': DiscoveryConnectionsApiModelToJSON(value['discoveryConnectionsDetail']),
        'RiskScore': value['riskScore'],
    };
}

