/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a model for exclude/include link setting.
 * @export
 * @interface ExcludedLinkModel
 */
export interface ExcludedLinkModel {
    /**
     * Gets or sets the pattern.
     * @type {string}
     * @memberof ExcludedLinkModel
     */
    regexPattern: string;
}

/**
 * Check if a given object implements the ExcludedLinkModel interface.
 */
export function instanceOfExcludedLinkModel(value: object): boolean {
    if (!('regexPattern' in value)) return false;
    return true;
}

export function ExcludedLinkModelFromJSON(json: any): ExcludedLinkModel {
    return ExcludedLinkModelFromJSONTyped(json, false);
}

export function ExcludedLinkModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExcludedLinkModel {
    if (json == null) {
        return json;
    }
    return {
        
        'regexPattern': json['RegexPattern'],
    };
}

export function ExcludedLinkModelToJSON(value?: ExcludedLinkModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'RegexPattern': value['regexPattern'],
    };
}

