/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Exclude filter.
 * @export
 * @interface ExcludeFilter
 */
export interface ExcludeFilter {
    /**
     * Gets or sets the excluded SLDS.
     * @type {Array<string>}
     * @memberof ExcludeFilter
     */
    excludedSlds?: Array<string>;
    /**
     * Gets or sets the excluded TLDS.
     * @type {Array<string>}
     * @memberof ExcludeFilter
     */
    excludedTlds?: Array<string>;
    /**
     * Gets or sets the excluded ip addresses.
     * @type {Array<string>}
     * @memberof ExcludeFilter
     */
    excludedIpAddresses?: Array<string>;
    /**
     * Gets or sets the excluded domains.
     * @type {Array<string>}
     * @memberof ExcludeFilter
     */
    excludedDomains?: Array<string>;
    /**
     * Gets or sets the excluded organizations.
     * @type {Array<string>}
     * @memberof ExcludeFilter
     */
    excludedOrganizations?: Array<string>;
}

/**
 * Check if a given object implements the ExcludeFilter interface.
 */
export function instanceOfExcludeFilter(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExcludeFilterFromJSON(json: any): ExcludeFilter {
    return ExcludeFilterFromJSONTyped(json, false);
}

export function ExcludeFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExcludeFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'excludedSlds': !exists(json, 'ExcludedSlds') ? undefined : json['ExcludedSlds'],
        'excludedTlds': !exists(json, 'ExcludedTlds') ? undefined : json['ExcludedTlds'],
        'excludedIpAddresses': !exists(json, 'ExcludedIpAddresses') ? undefined : json['ExcludedIpAddresses'],
        'excludedDomains': !exists(json, 'ExcludedDomains') ? undefined : json['ExcludedDomains'],
        'excludedOrganizations': !exists(json, 'ExcludedOrganizations') ? undefined : json['ExcludedOrganizations'],
    };
}

export function ExcludeFilterToJSON(value?: ExcludeFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ExcludedSlds': value.excludedSlds,
        'ExcludedTlds': value.excludedTlds,
        'ExcludedIpAddresses': value.excludedIpAddresses,
        'ExcludedDomains': value.excludedDomains,
        'ExcludedOrganizations': value.excludedOrganizations,
    };
}

