/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Base subscription license model for carrying out license data.
 * @export
 * @interface LicenseBaseModel
 */
export interface LicenseBaseModel {
    /**
     * Gets or sets the identifier.
     * @type {string}
     * @memberof LicenseBaseModel
     */
    id?: string;
    /**
     * Gets or sets a value indicating whether this license is active.
     * @type {boolean}
     * @memberof LicenseBaseModel
     */
    isActive?: boolean;
    /**
     * Gets or sets the key.
     * @type {string}
     * @memberof LicenseBaseModel
     */
    key?: string;
    /**
     * Gets or sets a value indicating whether shark scanning is enabled.
     * @type {boolean}
     * @memberof LicenseBaseModel
     */
    accountCanCreateSharkScanTask?: boolean;
}

/**
 * Check if a given object implements the LicenseBaseModel interface.
 */
export function instanceOfLicenseBaseModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LicenseBaseModelFromJSON(json: any): LicenseBaseModel {
    return LicenseBaseModelFromJSONTyped(json, false);
}

export function LicenseBaseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LicenseBaseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'isActive': !exists(json, 'IsActive') ? undefined : json['IsActive'],
        'key': !exists(json, 'Key') ? undefined : json['Key'],
        'accountCanCreateSharkScanTask': !exists(json, 'AccountCanCreateSharkScanTask') ? undefined : json['AccountCanCreateSharkScanTask'],
    };
}

export function LicenseBaseModelToJSON(value?: LicenseBaseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'IsActive': value.isActive,
        'Key': value.key,
        'AccountCanCreateSharkScanTask': value.accountCanCreateSharkScanTask,
    };
}

