/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ScheduledScanRecurrenceApiModel } from './ScheduledScanRecurrenceApiModel';
import {
    ScheduledScanRecurrenceApiModelFromJSON,
    ScheduledScanRecurrenceApiModelFromJSONTyped,
    ScheduledScanRecurrenceApiModelToJSON,
} from './ScheduledScanRecurrenceApiModel';

/**
 * Contains properties that required to start a scheduled scan according to profile specified.
 * @export
 * @interface NewScheduledWithProfileApiModel
 */
export interface NewScheduledWithProfileApiModel {
    /**
     * Gets or sets the profile name.
     * @type {string}
     * @memberof NewScheduledWithProfileApiModel
     */
    profileName: string;
    /**
     * Gets or sets the target URI.
     * @type {string}
     * @memberof NewScheduledWithProfileApiModel
     */
    targetUri: string;
    /**
     * Gets or sets the name.
     * @type {string}
     * @memberof NewScheduledWithProfileApiModel
     */
    name: string;
    /**
     * Gets or sets the next execution time.
     * Date string must be in the same format as in the account settings.
     * @type {string}
     * @memberof NewScheduledWithProfileApiModel
     */
    nextExecutionTime: string;
    /**
     * Gets or sets the run interval of scheduled scan.
     * @type {string}
     * @memberof NewScheduledWithProfileApiModel
     */
    scheduleRunType: NewScheduledWithProfileApiModelScheduleRunTypeEnum;
    /**
     * 
     * @type {ScheduledScanRecurrenceApiModel}
     * @memberof NewScheduledWithProfileApiModel
     */
    customRecurrence?: ScheduledScanRecurrenceApiModel;
}


/**
 * @export
 */
export const NewScheduledWithProfileApiModelScheduleRunTypeEnum = {
    Once: 'Once',
    Daily: 'Daily',
    Weekly: 'Weekly',
    Monthly: 'Monthly',
    Quarterly: 'Quarterly',
    Biannually: 'Biannually',
    Yearly: 'Yearly',
    Custom: 'Custom'
} as const;
export type NewScheduledWithProfileApiModelScheduleRunTypeEnum = typeof NewScheduledWithProfileApiModelScheduleRunTypeEnum[keyof typeof NewScheduledWithProfileApiModelScheduleRunTypeEnum];


/**
 * Check if a given object implements the NewScheduledWithProfileApiModel interface.
 */
export function instanceOfNewScheduledWithProfileApiModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "profileName" in value;
    isInstance = isInstance && "targetUri" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "nextExecutionTime" in value;
    isInstance = isInstance && "scheduleRunType" in value;

    return isInstance;
}

export function NewScheduledWithProfileApiModelFromJSON(json: any): NewScheduledWithProfileApiModel {
    return NewScheduledWithProfileApiModelFromJSONTyped(json, false);
}

export function NewScheduledWithProfileApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewScheduledWithProfileApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profileName': json['ProfileName'],
        'targetUri': json['TargetUri'],
        'name': json['Name'],
        'nextExecutionTime': json['NextExecutionTime'],
        'scheduleRunType': json['ScheduleRunType'],
        'customRecurrence': !exists(json, 'CustomRecurrence') ? undefined : ScheduledScanRecurrenceApiModelFromJSON(json['CustomRecurrence']),
    };
}

export function NewScheduledWithProfileApiModelToJSON(value?: NewScheduledWithProfileApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ProfileName': value.profileName,
        'TargetUri': value.targetUri,
        'Name': value.name,
        'NextExecutionTime': value.nextExecutionTime,
        'ScheduleRunType': value.scheduleRunType,
        'CustomRecurrence': ScheduledScanRecurrenceApiModelToJSON(value.customRecurrence),
    };
}

