/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RoleWebsiteGroupMappingApiModel } from './RoleWebsiteGroupMappingApiModel';
import {
    RoleWebsiteGroupMappingApiModelFromJSON,
    RoleWebsiteGroupMappingApiModelFromJSONTyped,
    RoleWebsiteGroupMappingApiModelToJSON,
} from './RoleWebsiteGroupMappingApiModel';

/**
 * 
 * @export
 * @interface NewTeamApiModel
 */
export interface NewTeamApiModel {
    /**
     * 
     * @type {Array<RoleWebsiteGroupMappingApiModel>}
     * @memberof NewTeamApiModel
     */
    roleWebsiteGroupMappings?: Array<RoleWebsiteGroupMappingApiModel>;
    /**
     * Role Name field
     * @type {string}
     * @memberof NewTeamApiModel
     */
    name: string;
    /**
     * users
     * @type {Array<string>}
     * @memberof NewTeamApiModel
     */
    members?: Array<string>;
}

/**
 * Check if a given object implements the NewTeamApiModel interface.
 */
export function instanceOfNewTeamApiModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function NewTeamApiModelFromJSON(json: any): NewTeamApiModel {
    return NewTeamApiModelFromJSONTyped(json, false);
}

export function NewTeamApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewTeamApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roleWebsiteGroupMappings': !exists(json, 'RoleWebsiteGroupMappings') ? undefined : ((json['RoleWebsiteGroupMappings'] as Array<any>).map(RoleWebsiteGroupMappingApiModelFromJSON)),
        'name': json['Name'],
        'members': !exists(json, 'Members') ? undefined : json['Members'],
    };
}

export function NewTeamApiModelToJSON(value?: NewTeamApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RoleWebsiteGroupMappings': value.roleWebsiteGroupMappings === undefined ? undefined : ((value.roleWebsiteGroupMappings as Array<any>).map(RoleWebsiteGroupMappingApiModelToJSON)),
        'Name': value.name,
        'Members': value.members,
    };
}

