/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Represents a scan time window item.
 * @export
 * @interface ScanTimeWindowItemViewModel
 */
export interface ScanTimeWindowItemViewModel {
    /**
     * Gets or sets the day.
     * @type {string}
     * @memberof ScanTimeWindowItemViewModel
     */
    day?: ScanTimeWindowItemViewModelDayEnum;
    /**
     * Gets or sets the left side of the time range as minutes past from midnight.
     * @type {number}
     * @memberof ScanTimeWindowItemViewModel
     */
    from?: number;
    /**
     * Gets or sets a value indicating whether scanning is allowed or not.
     * @type {boolean}
     * @memberof ScanTimeWindowItemViewModel
     */
    scanningAllowed?: boolean;
    /**
     * Gets or sets the right side of the time range as minutes past from midnight.
     * @type {number}
     * @memberof ScanTimeWindowItemViewModel
     */
    to?: number;
}


/**
 * @export
 */
export const ScanTimeWindowItemViewModelDayEnum = {
    Sunday: 'Sunday',
    Monday: 'Monday',
    Tuesday: 'Tuesday',
    Wednesday: 'Wednesday',
    Thursday: 'Thursday',
    Friday: 'Friday',
    Saturday: 'Saturday'
} as const;
export type ScanTimeWindowItemViewModelDayEnum = typeof ScanTimeWindowItemViewModelDayEnum[keyof typeof ScanTimeWindowItemViewModelDayEnum];


/**
 * Check if a given object implements the ScanTimeWindowItemViewModel interface.
 */
export function instanceOfScanTimeWindowItemViewModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScanTimeWindowItemViewModelFromJSON(json: any): ScanTimeWindowItemViewModel {
    return ScanTimeWindowItemViewModelFromJSONTyped(json, false);
}

export function ScanTimeWindowItemViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanTimeWindowItemViewModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'day': !exists(json, 'Day') ? undefined : json['Day'],
        'from': !exists(json, 'From') ? undefined : json['From'],
        'scanningAllowed': !exists(json, 'ScanningAllowed') ? undefined : json['ScanningAllowed'],
        'to': !exists(json, 'To') ? undefined : json['To'],
    };
}

export function ScanTimeWindowItemViewModelToJSON(value?: ScanTimeWindowItemViewModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Day': value.day,
        'From': value.from,
        'ScanningAllowed': value.scanningAllowed,
        'To': value.to,
    };
}

