/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ScheduledScanModel } from './ScheduledScanModel';
import {
    ScheduledScanModelFromJSON,
    ScheduledScanModelFromJSONTyped,
    ScheduledScanModelToJSON,
} from './ScheduledScanModel';

/**
 * Represents a model for carrying out a paged scheduled scan list.
 * @export
 * @interface ScheduledScanListApiResult
 */
export interface ScheduledScanListApiResult {
    /**
     * 
     * @type {number}
     * @memberof ScheduledScanListApiResult
     */
    firstItemOnPage?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ScheduledScanListApiResult
     */
    hasNextPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ScheduledScanListApiResult
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ScheduledScanListApiResult
     */
    isFirstPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ScheduledScanListApiResult
     */
    isLastPage?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ScheduledScanListApiResult
     */
    lastItemOnPage?: number;
    /**
     * 
     * @type {Array<ScheduledScanModel>}
     * @memberof ScheduledScanListApiResult
     */
    list?: Array<ScheduledScanModel>;
    /**
     * 
     * @type {number}
     * @memberof ScheduledScanListApiResult
     */
    pageCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ScheduledScanListApiResult
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof ScheduledScanListApiResult
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ScheduledScanListApiResult
     */
    totalItemCount?: number;
}

/**
 * Check if a given object implements the ScheduledScanListApiResult interface.
 */
export function instanceOfScheduledScanListApiResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScheduledScanListApiResultFromJSON(json: any): ScheduledScanListApiResult {
    return ScheduledScanListApiResultFromJSONTyped(json, false);
}

export function ScheduledScanListApiResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduledScanListApiResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstItemOnPage': !exists(json, 'FirstItemOnPage') ? undefined : json['FirstItemOnPage'],
        'hasNextPage': !exists(json, 'HasNextPage') ? undefined : json['HasNextPage'],
        'hasPreviousPage': !exists(json, 'HasPreviousPage') ? undefined : json['HasPreviousPage'],
        'isFirstPage': !exists(json, 'IsFirstPage') ? undefined : json['IsFirstPage'],
        'isLastPage': !exists(json, 'IsLastPage') ? undefined : json['IsLastPage'],
        'lastItemOnPage': !exists(json, 'LastItemOnPage') ? undefined : json['LastItemOnPage'],
        'list': !exists(json, 'List') ? undefined : ((json['List'] as Array<any>).map(ScheduledScanModelFromJSON)),
        'pageCount': !exists(json, 'PageCount') ? undefined : json['PageCount'],
        'pageNumber': !exists(json, 'PageNumber') ? undefined : json['PageNumber'],
        'pageSize': !exists(json, 'PageSize') ? undefined : json['PageSize'],
        'totalItemCount': !exists(json, 'TotalItemCount') ? undefined : json['TotalItemCount'],
    };
}

export function ScheduledScanListApiResultToJSON(value?: ScheduledScanListApiResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'FirstItemOnPage': value.firstItemOnPage,
        'HasNextPage': value.hasNextPage,
        'HasPreviousPage': value.hasPreviousPage,
        'IsFirstPage': value.isFirstPage,
        'IsLastPage': value.isLastPage,
        'LastItemOnPage': value.lastItemOnPage,
        'List': value.list === undefined ? undefined : ((value.list as Array<any>).map(ScheduledScanModelToJSON)),
        'PageCount': value.pageCount,
        'PageNumber': value.pageNumber,
        'PageSize': value.pageSize,
        'TotalItemCount': value.totalItemCount,
    };
}

