/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a scan policy setting, either general or specific to an engine.
 * @export
 * @interface SecurityCheckSetting
 */
export interface SecurityCheckSetting {
    /**
     * Gets or sets the name of this setting.
     * @type {string}
     * @memberof SecurityCheckSetting
     */
    name?: string;
    /**
     * Gets or sets the value of this setting.
     * @type {string}
     * @memberof SecurityCheckSetting
     */
    value?: string;
}

/**
 * Check if a given object implements the SecurityCheckSetting interface.
 */
export function instanceOfSecurityCheckSetting(value: object): boolean {
    return true;
}

export function SecurityCheckSettingFromJSON(json: any): SecurityCheckSetting {
    return SecurityCheckSettingFromJSONTyped(json, false);
}

export function SecurityCheckSettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityCheckSetting {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['Name'] == null ? undefined : json['Name'],
        'value': json['Value'] == null ? undefined : json['Value'],
    };
}

export function SecurityCheckSettingToJSON(value?: SecurityCheckSetting | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'Name': value['name'],
        'Value': value['value'],
    };
}

