/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FieldPairValue } from './FieldPairValue';
import {
    FieldPairValueFromJSON,
    FieldPairValueFromJSONTyped,
    FieldPairValueToJSON,
} from './FieldPairValue';
import type { IntegrationCustomFieldVm } from './IntegrationCustomFieldVm';
import {
    IntegrationCustomFieldVmFromJSON,
    IntegrationCustomFieldVmFromJSONTyped,
    IntegrationCustomFieldVmToJSON,
} from './IntegrationCustomFieldVm';
import type { IntegrationWizardResultModel } from './IntegrationWizardResultModel';
import {
    IntegrationWizardResultModelFromJSON,
    IntegrationWizardResultModelFromJSONTyped,
    IntegrationWizardResultModelToJSON,
} from './IntegrationWizardResultModel';

/**
 * 
 * @export
 * @interface ServiceNowVRMModel
 */
export interface ServiceNowVRMModel {
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    url: string;
    /**
     * Gets web hook URL.
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    readonly webhookUrl?: string;
    /**
     * Gets or sets the ServiceNow password for the user.
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    password: string;
    /**
     * 
     * @type {{ [key: string]: FieldPairValue; }}
     * @memberof ServiceNowVRMModel
     */
    fieldPairs?: { [key: string]: FieldPairValue; };
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    readonly resolvedStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    readonly reopenStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    readonly falsePositiveStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    readonly acceptedRiskStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    summaryFormat: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    cIMatchingColumn?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    cIMatchingColumnText?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    readonly type?: ServiceNowVRMModelTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    readonly genericErrorMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    readonly identifier?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    readonly testMessageBody?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    readonly testMessageTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceNowVRMModel
     */
    integrationVersion?: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    accountID?: string;
    /**
     * 
     * @type {Array<IntegrationCustomFieldVm>}
     * @memberof ServiceNowVRMModel
     */
    customFields?: Array<IntegrationCustomFieldVm>;
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    templateType?: ServiceNowVRMModelTemplateTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceNowVRMModel
     */
    titleFormat: string;
    /**
     * 
     * @type {IntegrationWizardResultModel}
     * @memberof ServiceNowVRMModel
     */
    integrationWizardResultModel?: IntegrationWizardResultModel;
}

/**
* @export
* @enum {string}
*/
export enum ServiceNowVRMModelTypeEnum {
    Jira = 'Jira',
    GitHub = 'GitHub',
    Tfs = 'TFS',
    FogBugz = 'FogBugz',
    ServiceNow = 'ServiceNow',
    Slack = 'Slack',
    GitLab = 'GitLab',
    Bitbucket = 'Bitbucket',
    Unfuddle = 'Unfuddle',
    Zapier = 'Zapier',
    AzureDevOps = 'AzureDevOps',
    Redmine = 'Redmine',
    Bugzilla = 'Bugzilla',
    Kafka = 'Kafka',
    PagerDuty = 'PagerDuty',
    MicrosoftTeams = 'MicrosoftTeams',
    Clubhouse = 'Clubhouse',
    Trello = 'Trello',
    Asana = 'Asana',
    Webhook = 'Webhook',
    Kenna = 'Kenna',
    Freshservice = 'Freshservice',
    YouTrack = 'YouTrack',
    NetsparkerEnterprise = 'NetsparkerEnterprise',
    Splunk = 'Splunk',
    Mattermost = 'Mattermost',
    Hashicorp = 'Hashicorp',
    PivotalTracker = 'PivotalTracker',
    CyberArk = 'CyberArk',
    DefectDojo = 'DefectDojo',
    JazzTeam = 'JazzTeam',
    AzureKeyVault = 'AzureKeyVault',
    ServiceNowVrm = 'ServiceNowVRM'
}
/**
* @export
* @enum {string}
*/
export enum ServiceNowVRMModelTemplateTypeEnum {
    Standard = 'Standard',
    Detailed = 'Detailed'
}


/**
 * Check if a given object implements the ServiceNowVRMModel interface.
 */
export function instanceOfServiceNowVRMModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "summaryFormat" in value;
    isInstance = isInstance && "titleFormat" in value;

    return isInstance;
}

export function ServiceNowVRMModelFromJSON(json: any): ServiceNowVRMModel {
    return ServiceNowVRMModelFromJSONTyped(json, false);
}

export function ServiceNowVRMModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceNowVRMModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['Username'],
        'url': json['Url'],
        'webhookUrl': !exists(json, 'WebhookUrl') ? undefined : json['WebhookUrl'],
        'password': json['Password'],
        'fieldPairs': !exists(json, 'FieldPairs') ? undefined : (mapValues(json['FieldPairs'], FieldPairValueFromJSON)),
        'resolvedStatus': !exists(json, 'ResolvedStatus') ? undefined : json['ResolvedStatus'],
        'reopenStatus': !exists(json, 'ReopenStatus') ? undefined : json['ReopenStatus'],
        'falsePositiveStatus': !exists(json, 'FalsePositiveStatus') ? undefined : json['FalsePositiveStatus'],
        'acceptedRiskStatus': !exists(json, 'AcceptedRiskStatus') ? undefined : json['AcceptedRiskStatus'],
        'summaryFormat': json['SummaryFormat'],
        'cIMatchingColumn': !exists(json, 'CIMatchingColumn') ? undefined : json['CIMatchingColumn'],
        'cIMatchingColumnText': !exists(json, 'CIMatchingColumnText') ? undefined : json['CIMatchingColumnText'],
        'type': !exists(json, 'Type') ? undefined : json['Type'],
        'genericErrorMessage': !exists(json, 'GenericErrorMessage') ? undefined : json['GenericErrorMessage'],
        'identifier': !exists(json, 'Identifier') ? undefined : json['Identifier'],
        'testMessageBody': !exists(json, 'TestMessageBody') ? undefined : json['TestMessageBody'],
        'testMessageTitle': !exists(json, 'TestMessageTitle') ? undefined : json['TestMessageTitle'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'integrationVersion': !exists(json, 'IntegrationVersion') ? undefined : json['IntegrationVersion'],
        'accountID': !exists(json, 'AccountID') ? undefined : json['AccountID'],
        'customFields': !exists(json, 'CustomFields') ? undefined : ((json['CustomFields'] as Array<any>).map(IntegrationCustomFieldVmFromJSON)),
        'templateType': !exists(json, 'TemplateType') ? undefined : json['TemplateType'],
        'titleFormat': json['TitleFormat'],
        'integrationWizardResultModel': !exists(json, 'IntegrationWizardResultModel') ? undefined : IntegrationWizardResultModelFromJSON(json['IntegrationWizardResultModel']),
    };
}

export function ServiceNowVRMModelToJSON(value?: ServiceNowVRMModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Username': value.username,
        'Url': value.url,
        'Password': value.password,
        'FieldPairs': value.fieldPairs === undefined ? undefined : (mapValues(value.fieldPairs, FieldPairValueToJSON)),
        'SummaryFormat': value.summaryFormat,
        'CIMatchingColumn': value.cIMatchingColumn,
        'CIMatchingColumnText': value.cIMatchingColumnText,
        'Name': value.name,
        'IntegrationVersion': value.integrationVersion,
        'AccountID': value.accountID,
        'CustomFields': value.customFields === undefined ? undefined : ((value.customFields as Array<any>).map(IntegrationCustomFieldVmToJSON)),
        'TemplateType': value.templateType,
        'TitleFormat': value.titleFormat,
        'IntegrationWizardResultModel': IntegrationWizardResultModelToJSON(value.integrationWizardResultModel),
    };
}

