/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IntegrationCustomFieldVm } from './IntegrationCustomFieldVm';
import {
    IntegrationCustomFieldVmFromJSON,
    IntegrationCustomFieldVmFromJSONTyped,
    IntegrationCustomFieldVmToJSON,
} from './IntegrationCustomFieldVm';
import type { IntegrationWizardResultModel } from './IntegrationWizardResultModel';
import {
    IntegrationWizardResultModelFromJSON,
    IntegrationWizardResultModelFromJSONTyped,
    IntegrationWizardResultModelToJSON,
} from './IntegrationWizardResultModel';

/**
 * The Slack integration info
 * @export
 * @interface SlackIntegrationInfoModel
 */
export interface SlackIntegrationInfoModel {
    /**
     * Gets or sets the Webhook URL.
     * @type {string}
     * @memberof SlackIntegrationInfoModel
     */
    incomingWebhookUrl: string;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegrationInfoModel
     */
    readonly type?: SlackIntegrationInfoModelTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegrationInfoModel
     */
    readonly genericErrorMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegrationInfoModel
     */
    readonly identifier?: string;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegrationInfoModel
     */
    readonly testMessageBody?: string;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegrationInfoModel
     */
    readonly testMessageTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegrationInfoModel
     */
    readonly webhookUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegrationInfoModel
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof SlackIntegrationInfoModel
     */
    integrationVersion?: number;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegrationInfoModel
     */
    accountID?: string;
    /**
     * 
     * @type {Array<IntegrationCustomFieldVm>}
     * @memberof SlackIntegrationInfoModel
     */
    customFields?: Array<IntegrationCustomFieldVm>;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegrationInfoModel
     */
    templateType?: SlackIntegrationInfoModelTemplateTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegrationInfoModel
     */
    reopenStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegrationInfoModel
     */
    resolvedStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegrationInfoModel
     */
    titleFormat: string;
    /**
     * 
     * @type {IntegrationWizardResultModel}
     * @memberof SlackIntegrationInfoModel
     */
    integrationWizardResultModel?: IntegrationWizardResultModel;
}

/**
* @export
* @enum {string}
*/
export enum SlackIntegrationInfoModelTypeEnum {
    NetsparkerEnterprise = 'NetsparkerEnterprise',
    Webhook = 'Webhook',
    Zapier = 'Zapier',
    Slack = 'Slack',
    Mattermost = 'Mattermost',
    MicrosoftTeams = 'MicrosoftTeams',
    AzureDevOps = 'AzureDevOps',
    Bitbucket = 'Bitbucket',
    Bugzilla = 'Bugzilla',
    Clubhouse = 'Clubhouse',
    DefectDojo = 'DefectDojo',
    PivotalTracker = 'PivotalTracker',
    Jira = 'Jira',
    FogBugz = 'FogBugz',
    GitHub = 'GitHub',
    PagerDuty = 'PagerDuty',
    Kafka = 'Kafka',
    Kenna = 'Kenna',
    Redmine = 'Redmine',
    ServiceNow = 'ServiceNow',
    Tfs = 'TFS',
    Unfuddle = 'Unfuddle',
    YouTrack = 'YouTrack',
    Freshservice = 'Freshservice',
    Splunk = 'Splunk',
    JazzTeam = 'JazzTeam',
    ServiceNowVrm = 'ServiceNowVRM',
    Asana = 'Asana',
    Trello = 'Trello',
    Hashicorp = 'Hashicorp',
    CyberArk = 'CyberArk',
    AzureKeyVault = 'AzureKeyVault',
    GitLab = 'GitLab'
}
/**
* @export
* @enum {string}
*/
export enum SlackIntegrationInfoModelTemplateTypeEnum {
    Standard = 'Standard',
    Detailed = 'Detailed'
}


/**
 * Check if a given object implements the SlackIntegrationInfoModel interface.
 */
export function instanceOfSlackIntegrationInfoModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "incomingWebhookUrl" in value;
    isInstance = isInstance && "titleFormat" in value;

    return isInstance;
}

export function SlackIntegrationInfoModelFromJSON(json: any): SlackIntegrationInfoModel {
    return SlackIntegrationInfoModelFromJSONTyped(json, false);
}

export function SlackIntegrationInfoModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SlackIntegrationInfoModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'incomingWebhookUrl': json['IncomingWebhookUrl'],
        'type': !exists(json, 'Type') ? undefined : json['Type'],
        'genericErrorMessage': !exists(json, 'GenericErrorMessage') ? undefined : json['GenericErrorMessage'],
        'identifier': !exists(json, 'Identifier') ? undefined : json['Identifier'],
        'testMessageBody': !exists(json, 'TestMessageBody') ? undefined : json['TestMessageBody'],
        'testMessageTitle': !exists(json, 'TestMessageTitle') ? undefined : json['TestMessageTitle'],
        'webhookUrl': !exists(json, 'WebhookUrl') ? undefined : json['WebhookUrl'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'integrationVersion': !exists(json, 'IntegrationVersion') ? undefined : json['IntegrationVersion'],
        'accountID': !exists(json, 'AccountID') ? undefined : json['AccountID'],
        'customFields': !exists(json, 'CustomFields') ? undefined : ((json['CustomFields'] as Array<any>).map(IntegrationCustomFieldVmFromJSON)),
        'templateType': !exists(json, 'TemplateType') ? undefined : json['TemplateType'],
        'reopenStatus': !exists(json, 'ReopenStatus') ? undefined : json['ReopenStatus'],
        'resolvedStatus': !exists(json, 'ResolvedStatus') ? undefined : json['ResolvedStatus'],
        'titleFormat': json['TitleFormat'],
        'integrationWizardResultModel': !exists(json, 'IntegrationWizardResultModel') ? undefined : IntegrationWizardResultModelFromJSON(json['IntegrationWizardResultModel']),
    };
}

export function SlackIntegrationInfoModelToJSON(value?: SlackIntegrationInfoModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'IncomingWebhookUrl': value.incomingWebhookUrl,
        'Name': value.name,
        'IntegrationVersion': value.integrationVersion,
        'AccountID': value.accountID,
        'CustomFields': value.customFields === undefined ? undefined : ((value.customFields as Array<any>).map(IntegrationCustomFieldVmToJSON)),
        'TemplateType': value.templateType,
        'ReopenStatus': value.reopenStatus,
        'ResolvedStatus': value.resolvedStatus,
        'TitleFormat': value.titleFormat,
        'IntegrationWizardResultModel': IntegrationWizardResultModelToJSON(value.integrationWizardResultModel),
    };
}

