/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrelloMember
 */
export interface TrelloMember {
    /**
     * 
     * @type {boolean}
     * @memberof TrelloMember
     */
    confirmed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TrelloMember
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof TrelloMember
     */
    fullname?: string;
    /**
     * 
     * @type {string}
     * @memberof TrelloMember
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TrelloMember
     */
    shortUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof TrelloMember
     */
    username?: string;
}

/**
 * Check if a given object implements the TrelloMember interface.
 */
export function instanceOfTrelloMember(value: object): boolean {
    return true;
}

export function TrelloMemberFromJSON(json: any): TrelloMember {
    return TrelloMemberFromJSONTyped(json, false);
}

export function TrelloMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrelloMember {
    if (json == null) {
        return json;
    }
    return {
        
        'confirmed': json['confirmed'] == null ? undefined : json['confirmed'],
        'email': json['email'] == null ? undefined : json['email'],
        'fullname': json['fullname'] == null ? undefined : json['fullname'],
        'id': json['id'] == null ? undefined : json['id'],
        'shortUrl': json['shortUrl'] == null ? undefined : json['shortUrl'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function TrelloMemberToJSON(value?: TrelloMember | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'confirmed': value['confirmed'],
        'email': value['email'],
        'fullname': value['fullname'],
        'id': value['id'],
        'shortUrl': value['shortUrl'],
        'username': value['username'],
    };
}

