/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrelloBoard } from './TrelloBoard';
import {
    TrelloBoardFromJSON,
    TrelloBoardFromJSONTyped,
    TrelloBoardToJSON,
} from './TrelloBoard';
import type { TrelloList } from './TrelloList';
import {
    TrelloListFromJSON,
    TrelloListFromJSONTyped,
    TrelloListToJSON,
} from './TrelloList';
import type { TrelloMember } from './TrelloMember';
import {
    TrelloMemberFromJSON,
    TrelloMemberFromJSONTyped,
    TrelloMemberToJSON,
} from './TrelloMember';
import type { TrelloLabel } from './TrelloLabel';
import {
    TrelloLabelFromJSON,
    TrelloLabelFromJSONTyped,
    TrelloLabelToJSON,
} from './TrelloLabel';
import type { IntegrationWizardResultModel } from './IntegrationWizardResultModel';
import {
    IntegrationWizardResultModelFromJSON,
    IntegrationWizardResultModelFromJSONTyped,
    IntegrationWizardResultModelToJSON,
} from './IntegrationWizardResultModel';
import type { IntegrationCustomFieldVm } from './IntegrationCustomFieldVm';
import {
    IntegrationCustomFieldVmFromJSON,
    IntegrationCustomFieldVmFromJSONTyped,
    IntegrationCustomFieldVmToJSON,
} from './IntegrationCustomFieldVm';

/**
 * The Trello integration info
 * @export
 * @interface TrelloIntegrationInfoModel
 */
export interface TrelloIntegrationInfoModel {
    /**
     * The API Key for API requests.
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    apiKey: string;
    /**
     * The Token ID identifier.
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    token: string;
    /**
     * The List identifier.
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    listId: string;
    /**
     * 
     * @type {IntegrationWizardResultModel}
     * @memberof TrelloIntegrationInfoModel
     */
    integrationWizardResultModel?: IntegrationWizardResultModel;
    /**
     * The Board identifier.
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    boardId: string;
    /**
     * The TrelloBoard List.
     * @type {Array<TrelloBoard>}
     * @memberof TrelloIntegrationInfoModel
     */
    boardIds?: Array<TrelloBoard>;
    /**
     * The TrelloList List.
     * @type {Array<TrelloList>}
     * @memberof TrelloIntegrationInfoModel
     */
    lists?: Array<TrelloList>;
    /**
     * The TrelloMember List.
     * @type {Array<TrelloMember>}
     * @memberof TrelloIntegrationInfoModel
     */
    members?: Array<TrelloMember>;
    /**
     * The TrelloLabel List.
     * @type {Array<TrelloLabel>}
     * @memberof TrelloIntegrationInfoModel
     */
    labels?: Array<TrelloLabel>;
    /**
     * Comma-separated Member  identifiers.
     * @type {Array<string>}
     * @memberof TrelloIntegrationInfoModel
     */
    memberIds?: Array<string>;
    /**
     * Comma-separated Label identifiers.
     * @type {Array<string>}
     * @memberof TrelloIntegrationInfoModel
     */
    labelIds?: Array<string>;
    /**
     * Comma-separated Label to convert string identifiers.
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    readonly labelIdsSelected?: string;
    /**
     * Comma-separated Member to convert string identifiers.
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    readonly memberIdsSelected?: string;
    /**
     * The days when incident is due from the time that issue is created on.
     * @type {number}
     * @memberof TrelloIntegrationInfoModel
     */
    dueDays: number;
    /**
     * 
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    readonly type?: TrelloIntegrationInfoModelTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    readonly genericErrorMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    readonly identifier?: string;
    /**
     * 
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    readonly testMessageBody?: string;
    /**
     * 
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    readonly testMessageTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    readonly webhookUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof TrelloIntegrationInfoModel
     */
    integrationVersion?: number;
    /**
     * 
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    accountID?: string;
    /**
     * 
     * @type {Array<IntegrationCustomFieldVm>}
     * @memberof TrelloIntegrationInfoModel
     */
    customFields?: Array<IntegrationCustomFieldVm>;
    /**
     * 
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    templateType?: TrelloIntegrationInfoModelTemplateTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    reopenStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    resolvedStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    titleFormat: string;
    /**
     * 
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TrelloIntegrationInfoModel
     */
    state?: TrelloIntegrationInfoModelStateEnum;
}


/**
 * @export
 */
export const TrelloIntegrationInfoModelTypeEnum = {
    Jira: 'Jira',
    GitHub: 'GitHub',
    Tfs: 'TFS',
    FogBugz: 'FogBugz',
    ServiceNow: 'ServiceNow',
    Slack: 'Slack',
    GitLab: 'GitLab',
    Bitbucket: 'Bitbucket',
    Unfuddle: 'Unfuddle',
    Zapier: 'Zapier',
    AzureDevOps: 'AzureDevOps',
    Redmine: 'Redmine',
    Bugzilla: 'Bugzilla',
    Kafka: 'Kafka',
    PagerDuty: 'PagerDuty',
    MicrosoftTeams: 'MicrosoftTeams',
    Clubhouse: 'Clubhouse',
    Trello: 'Trello',
    Asana: 'Asana',
    Webhook: 'Webhook',
    Kenna: 'Kenna',
    Freshservice: 'Freshservice',
    YouTrack: 'YouTrack',
    NetsparkerEnterprise: 'NetsparkerEnterprise',
    Splunk: 'Splunk',
    Mattermost: 'Mattermost',
    Hashicorp: 'Hashicorp',
    PivotalTracker: 'PivotalTracker',
    CyberArk: 'CyberArk',
    DefectDojo: 'DefectDojo',
    JazzTeam: 'JazzTeam',
    AzureKeyVault: 'AzureKeyVault',
    ServiceNowVrm: 'ServiceNowVRM'
} as const;
export type TrelloIntegrationInfoModelTypeEnum = typeof TrelloIntegrationInfoModelTypeEnum[keyof typeof TrelloIntegrationInfoModelTypeEnum];

/**
 * @export
 */
export const TrelloIntegrationInfoModelTemplateTypeEnum = {
    Standard: 'Standard',
    Detailed: 'Detailed'
} as const;
export type TrelloIntegrationInfoModelTemplateTypeEnum = typeof TrelloIntegrationInfoModelTemplateTypeEnum[keyof typeof TrelloIntegrationInfoModelTemplateTypeEnum];

/**
 * @export
 */
export const TrelloIntegrationInfoModelStateEnum = {
    Active: 'Active',
    Suspended: 'Suspended'
} as const;
export type TrelloIntegrationInfoModelStateEnum = typeof TrelloIntegrationInfoModelStateEnum[keyof typeof TrelloIntegrationInfoModelStateEnum];


/**
 * Check if a given object implements the TrelloIntegrationInfoModel interface.
 */
export function instanceOfTrelloIntegrationInfoModel(value: object): boolean {
    if (!('apiKey' in value)) return false;
    if (!('token' in value)) return false;
    if (!('listId' in value)) return false;
    if (!('boardId' in value)) return false;
    if (!('dueDays' in value)) return false;
    if (!('titleFormat' in value)) return false;
    return true;
}

export function TrelloIntegrationInfoModelFromJSON(json: any): TrelloIntegrationInfoModel {
    return TrelloIntegrationInfoModelFromJSONTyped(json, false);
}

export function TrelloIntegrationInfoModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrelloIntegrationInfoModel {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['ApiKey'],
        'token': json['Token'],
        'listId': json['ListId'],
        'integrationWizardResultModel': json['IntegrationWizardResultModel'] == null ? undefined : IntegrationWizardResultModelFromJSON(json['IntegrationWizardResultModel']),
        'boardId': json['BoardId'],
        'boardIds': json['BoardIds'] == null ? undefined : ((json['BoardIds'] as Array<any>).map(TrelloBoardFromJSON)),
        'lists': json['Lists'] == null ? undefined : ((json['Lists'] as Array<any>).map(TrelloListFromJSON)),
        'members': json['Members'] == null ? undefined : ((json['Members'] as Array<any>).map(TrelloMemberFromJSON)),
        'labels': json['Labels'] == null ? undefined : ((json['Labels'] as Array<any>).map(TrelloLabelFromJSON)),
        'memberIds': json['MemberIds'] == null ? undefined : json['MemberIds'],
        'labelIds': json['LabelIds'] == null ? undefined : json['LabelIds'],
        'labelIdsSelected': json['LabelIdsSelected'] == null ? undefined : json['LabelIdsSelected'],
        'memberIdsSelected': json['MemberIdsSelected'] == null ? undefined : json['MemberIdsSelected'],
        'dueDays': json['DueDays'],
        'type': json['Type'] == null ? undefined : json['Type'],
        'genericErrorMessage': json['GenericErrorMessage'] == null ? undefined : json['GenericErrorMessage'],
        'identifier': json['Identifier'] == null ? undefined : json['Identifier'],
        'testMessageBody': json['TestMessageBody'] == null ? undefined : json['TestMessageBody'],
        'testMessageTitle': json['TestMessageTitle'] == null ? undefined : json['TestMessageTitle'],
        'webhookUrl': json['WebhookUrl'] == null ? undefined : json['WebhookUrl'],
        'name': json['Name'] == null ? undefined : json['Name'],
        'integrationVersion': json['IntegrationVersion'] == null ? undefined : json['IntegrationVersion'],
        'accountID': json['AccountID'] == null ? undefined : json['AccountID'],
        'customFields': json['CustomFields'] == null ? undefined : ((json['CustomFields'] as Array<any>).map(IntegrationCustomFieldVmFromJSON)),
        'templateType': json['TemplateType'] == null ? undefined : json['TemplateType'],
        'reopenStatus': json['ReopenStatus'] == null ? undefined : json['ReopenStatus'],
        'resolvedStatus': json['ResolvedStatus'] == null ? undefined : json['ResolvedStatus'],
        'titleFormat': json['TitleFormat'],
        'id': json['Id'] == null ? undefined : json['Id'],
        'state': json['State'] == null ? undefined : json['State'],
    };
}

export function TrelloIntegrationInfoModelToJSON(value?: Omit<TrelloIntegrationInfoModel, 'LabelIdsSelected'|'MemberIdsSelected'|'Type'|'GenericErrorMessage'|'Identifier'|'TestMessageBody'|'TestMessageTitle'|'WebhookUrl'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ApiKey': value['apiKey'],
        'Token': value['token'],
        'ListId': value['listId'],
        'IntegrationWizardResultModel': IntegrationWizardResultModelToJSON(value['integrationWizardResultModel']),
        'BoardId': value['boardId'],
        'BoardIds': value['boardIds'] == null ? undefined : ((value['boardIds'] as Array<any>).map(TrelloBoardToJSON)),
        'Lists': value['lists'] == null ? undefined : ((value['lists'] as Array<any>).map(TrelloListToJSON)),
        'Members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(TrelloMemberToJSON)),
        'Labels': value['labels'] == null ? undefined : ((value['labels'] as Array<any>).map(TrelloLabelToJSON)),
        'MemberIds': value['memberIds'],
        'LabelIds': value['labelIds'],
        'DueDays': value['dueDays'],
        'Name': value['name'],
        'IntegrationVersion': value['integrationVersion'],
        'AccountID': value['accountID'],
        'CustomFields': value['customFields'] == null ? undefined : ((value['customFields'] as Array<any>).map(IntegrationCustomFieldVmToJSON)),
        'TemplateType': value['templateType'],
        'ReopenStatus': value['reopenStatus'],
        'ResolvedStatus': value['resolvedStatus'],
        'TitleFormat': value['titleFormat'],
        'Id': value['id'],
        'State': value['state'],
    };
}

