/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Represents an URL Rewrite rule.
 * @export
 * @interface UrlRewriteRuleModel
 */
export interface UrlRewriteRuleModel {
    /**
     * Gets or sets the path placeholders.
     * @type {string}
     * @memberof UrlRewriteRuleModel
     */
    placeholderPattern?: string;
    /**
     * Gets or sets the pattern.
     * @type {string}
     * @memberof UrlRewriteRuleModel
     */
    regexPattern?: string;
}

/**
 * Check if a given object implements the UrlRewriteRuleModel interface.
 */
export function instanceOfUrlRewriteRuleModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UrlRewriteRuleModelFromJSON(json: any): UrlRewriteRuleModel {
    return UrlRewriteRuleModelFromJSONTyped(json, false);
}

export function UrlRewriteRuleModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UrlRewriteRuleModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'placeholderPattern': !exists(json, 'PlaceholderPattern') ? undefined : json['PlaceholderPattern'],
        'regexPattern': !exists(json, 'RegexPattern') ? undefined : json['RegexPattern'],
    };
}

export function UrlRewriteRuleModelToJSON(value?: UrlRewriteRuleModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'PlaceholderPattern': value.placeholderPattern,
        'RegexPattern': value.regexPattern,
    };
}

