/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The health check model for user
 * @export
 * @interface UserHealthCheckApiModel
 */
export interface UserHealthCheckApiModel {
    /**
     * Gets or sets user's date format
     * @type {string}
     * @memberof UserHealthCheckApiModel
     */
    dateFormat?: string;
    /**
     * Gets or sets user display name
     * @type {string}
     * @memberof UserHealthCheckApiModel
     */
    displayName?: string;
    /**
     * Gets or sets Email
     * @type {string}
     * @memberof UserHealthCheckApiModel
     */
    email?: string;
    /**
     * Gets or sets Alternate Email
     * @type {string}
     * @memberof UserHealthCheckApiModel
     */
    alternateLoginEmail?: string;
    /**
     * Gets or sets user's time info
     * @type {string}
     * @memberof UserHealthCheckApiModel
     */
    timeZoneInfo?: string;
}

/**
 * Check if a given object implements the UserHealthCheckApiModel interface.
 */
export function instanceOfUserHealthCheckApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserHealthCheckApiModelFromJSON(json: any): UserHealthCheckApiModel {
    return UserHealthCheckApiModelFromJSONTyped(json, false);
}

export function UserHealthCheckApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserHealthCheckApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dateFormat': !exists(json, 'DateFormat') ? undefined : json['DateFormat'],
        'displayName': !exists(json, 'DisplayName') ? undefined : json['DisplayName'],
        'email': !exists(json, 'Email') ? undefined : json['Email'],
        'alternateLoginEmail': !exists(json, 'AlternateLoginEmail') ? undefined : json['AlternateLoginEmail'],
        'timeZoneInfo': !exists(json, 'TimeZoneInfo') ? undefined : json['TimeZoneInfo'],
    };
}

export function UserHealthCheckApiModelToJSON(value?: UserHealthCheckApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DateFormat': value.dateFormat,
        'DisplayName': value.displayName,
        'Email': value.email,
        'AlternateLoginEmail': value.alternateLoginEmail,
        'TimeZoneInfo': value.timeZoneInfo,
    };
}

