/* tslint:disable */
/* eslint-disable */
/**
 * Invicti Enterprise API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a model for carrying out website group data.
 * @export
 * @interface WebsiteGroupApiModel
 */
export interface WebsiteGroupApiModel {
    /**
     * Gets or sets the total websites.
     * @type {number}
     * @memberof WebsiteGroupApiModel
     */
    totalWebsites?: number;
    /**
     * Gets or sets the date which this website group created at.
     * @type {Date}
     * @memberof WebsiteGroupApiModel
     */
    createdAt?: Date;
    /**
     * Gets or sets the date which this website group was updated at.
     * @type {Date}
     * @memberof WebsiteGroupApiModel
     */
    updatedAt?: Date;
    /**
     * Gets or sets the website group identifier.
     * @type {string}
     * @memberof WebsiteGroupApiModel
     */
    id: string;
    /**
     * Gets or sets the website group name.
     * @type {string}
     * @memberof WebsiteGroupApiModel
     */
    name: string;
    /**
     * Gets or sets the website group description.
     * @type {string}
     * @memberof WebsiteGroupApiModel
     */
    description?: string;
    /**
     * Tags
     * @type {Array<string>}
     * @memberof WebsiteGroupApiModel
     */
    tags?: Array<string>;
}

/**
 * Check if a given object implements the WebsiteGroupApiModel interface.
 */
export function instanceOfWebsiteGroupApiModel(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    return true;
}

export function WebsiteGroupApiModelFromJSON(json: any): WebsiteGroupApiModel {
    return WebsiteGroupApiModelFromJSONTyped(json, false);
}

export function WebsiteGroupApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebsiteGroupApiModel {
    if (json == null) {
        return json;
    }
    return {
        
        'totalWebsites': json['TotalWebsites'] == null ? undefined : json['TotalWebsites'],
        'createdAt': json['CreatedAt'] == null ? undefined : (new Date(json['CreatedAt'])),
        'updatedAt': json['UpdatedAt'] == null ? undefined : (new Date(json['UpdatedAt'])),
        'id': json['Id'],
        'name': json['Name'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'tags': json['Tags'] == null ? undefined : json['Tags'],
    };
}

export function WebsiteGroupApiModelToJSON(value?: WebsiteGroupApiModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'TotalWebsites': value['totalWebsites'],
        'CreatedAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'UpdatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'Id': value['id'],
        'Name': value['name'],
        'Description': value['description'],
        'Tags': value['tags'],
    };
}

